# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

import asyncio
import json
import re

from microsoft_teams.api import (
    MessageActivity,
    MessageActivityInput,
    CitationAppearance,
    CitationIconName,
    MessageSubmitActionInvokeActivity,
    SensitiveUsageEntity,
    SensitiveUsage,
    MessageFetchTaskInvokeActivity,
    TaskModuleInvokeResponse,
    AdaptiveCardAttachment,
    card_attachment,
    CardTaskModuleTaskInfo, 
    TaskModuleContinueResponse,
)
from microsoft_teams.apps import ActivityContext, App
from microsoft_teams.cards import AdaptiveCard, SubmitAction, TextBlock, TextInput

app = App()

@app.on_message_submit_feedback
async def handle_feedback(ctx: ActivityContext[MessageSubmitActionInvokeActivity]):
    action_value = ctx.activity.value.action_value
    reaction = action_value.reaction
    raw_feedback = action_value.feedback
    feedback_text = json.loads(raw_feedback).get("feedbackText") or "No feedback was provided."
    await ctx.send(MessageActivityInput(text=f"Provided reaction: {reaction}<br> Feedback: {feedback_text}"))
    

@app.on_message_fetch_task
async def handle_feedback_fetch_task(ctx: ActivityContext[MessageFetchTaskInvokeActivity]):
    card = AdaptiveCard(
        version="1.4",
        body=[
            TextBlock(text="Tell us more about your feedback:"),
            TextInput(id="feedbackText", placeholder="Enter your feedback here...", is_multiline=True),
        ],
        actions=[
            SubmitAction(title="Submit"),
        ],
    )
    return TaskModuleInvokeResponse(
        task=TaskModuleContinueResponse(
            value=CardTaskModuleTaskInfo(
                title="Feedback",
                card=card_attachment(AdaptiveCardAttachment(content=card)),
            )
        )
    )


@app.on_message_pattern(re.compile(r"label", re.IGNORECASE))
async def add_ai_label(ctx: ActivityContext[MessageActivity]):
    await ctx.send(
        MessageActivityInput(
            text="Hi, this message is generated by AI",
        ).add_ai_generated()
    )

@app.on_message_pattern(re.compile(r"sensitivity", re.IGNORECASE))
async def add_sensitivity_label(ctx: ActivityContext[MessageActivity]):
    msg = MessageActivityInput(
        text="This is an example of a sensitivity label that help users identify the confidentiality of a message",
    )
    sensitive_usage_entity = SensitiveUsageEntity(
        usage_info=SensitiveUsage(at_type="CreativeWork", name="Confidential \\ Contoso FTE", description="Please be mindful of sharing outside of your team")
    )
    msg.add_entity(sensitive_usage_entity)
    await ctx.send(msg)


@app.on_message_pattern(re.compile(r"feedback", re.IGNORECASE))
async def add_feedback_buttons(ctx: ActivityContext[MessageActivity]):
    await ctx.send(
        MessageActivityInput(
            text="This is an example of a feedback button - this helps to provide feedback for a message",
        ).add_feedback('custom')
    )

@app.on_message_pattern(re.compile(r"citation", re.IGNORECASE))
async def add_citations(ctx: ActivityContext[MessageActivity]):
    await ctx.send(
        MessageActivityInput(
            text="Hey I'm a friendly AI bot. This message is generated through AI [1]",
        ).add_citation(
            position=1,
            appearance=CitationAppearance(
                name="AI messages bot",
                url="https://example.com/claim-1",
                abstract="Excerpt description",
                text=AdaptiveCard(version="1.6", body=[TextBlock(text="Adaptive Card text")]).model_dump_json(by_alias=True, exclude_none=True),
                keywords=["keyword 1", "keyword 2", "keyword 3"],
                icon=CitationIconName.MICROSOFT_WORD,
            ),
        )
    )

@app.on_message
async def handle_message(ctx: ActivityContext[MessageActivity]):
    await ctx.send("Welcome to the AI bot! Try sending messages with keywords like 'label', 'sensitivity', 'feedback', or 'citation' to see different AI features.")

if __name__ == "__main__":
    asyncio.run(app.start())
