//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCompleteSample {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppCompleteSample.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot resume!.
        /// </summary>
        internal static string AuthCallbackResumeError {
            get {
                return ResourceManager.GetString("AuthCallbackResumeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered numbered is not valid!, please login again..
        /// </summary>
        internal static string AuthMagicNumberNotMacthed {
            get {
                return ResourceManager.GetString("AuthMagicNumberNotMacthed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Clicked below any OAuth 2.0 Samples (Bot Command - &quot;auth&quot;).
        /// </summary>
        internal static string AuthSampleCardTitle {
            get {
                return ResourceManager.GetString("AuthSampleCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, welcome to begin dialog.
        /// </summary>
        internal static string BeginDialog {
            get {
                return ResourceManager.GetString("BeginDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin dialog end.
        /// </summary>
        internal static string BeginDialogEnd {
            get {
                return ResourceManager.GetString("BeginDialogEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, I&apos;m your new bot!.
        /// </summary>
        internal static string BotWelcomeMessage {
            get {
                return ResourceManager.GetString("BotWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        internal static string CaptionChatButton {
            get {
                return ResourceManager.GetString("CaptionChatButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoke Hello Dialog.
        /// </summary>
        internal static string CaptionInvokeHelloDailog {
            get {
                return ResourceManager.GetString("CaptionInvokeHelloDailog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoke Multi Dialog.
        /// </summary>
        internal static string CaptionInvokeMultiDailog {
            get {
                return ResourceManager.GetString("CaptionInvokeMultiDailog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auth.
        /// </summary>
        internal static string cmdAuthSampleDialog {
            get {
                return ResourceManager.GetString("cmdAuthSampleDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deep link.
        /// </summary>
        internal static string cmdDeepLink {
            get {
                return ResourceManager.GetString("cmdDeepLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dialog flow.
        /// </summary>
        internal static string cmdDialogFlow {
            get {
                return ResourceManager.GetString("cmdDialogFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to display cards.
        /// </summary>
        internal static string cmdDisplayCards {
            get {
                return ResourceManager.GetString("cmdDisplayCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last dialog.
        /// </summary>
        internal static string cmdFetchLastDialog {
            get {
                return ResourceManager.GetString("cmdFetchLastDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to names.
        /// </summary>
        internal static string cmdFetchRoster {
            get {
                return ResourceManager.GetString("cmdFetchRoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to team info.
        /// </summary>
        internal static string cmdGetTeamInfo {
            get {
                return ResourceManager.GetString("cmdGetTeamInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hi.
        /// </summary>
        internal static string cmdHelloDialog {
            get {
                return ResourceManager.GetString("cmdHelloDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to localtime.
        /// </summary>
        internal static string cmdLocalTime {
            get {
                return ResourceManager.GetString("cmdLocalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to msgback.
        /// </summary>
        internal static string cmdMessageBack {
            get {
                return ResourceManager.GetString("cmdMessageBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to multi dialog 1.
        /// </summary>
        internal static string cmdMultiDialog1 {
            get {
                return ResourceManager.GetString("cmdMultiDialog1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to multi dialog 2.
        /// </summary>
        internal static string cmdMultiDialog2 {
            get {
                return ResourceManager.GetString("cmdMultiDialog2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        internal static string cmdNoDisplayCards {
            get {
                return ResourceManager.GetString("cmdNoDisplayCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actionable Card.
        /// </summary>
        internal static string cmdO365ConnectorCardActionableMessages {
            get {
                return ResourceManager.GetString("cmdO365ConnectorCardActionableMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to signin.
        /// </summary>
        internal static string cmdPopUpSignIn {
            get {
                return ResourceManager.GetString("cmdPopUpSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prompt.
        /// </summary>
        internal static string cmdPrompt {
            get {
                return ResourceManager.GetString("cmdPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to roster.
        /// </summary>
        internal static string cmdRosterPayload {
            get {
                return ResourceManager.GetString("cmdRosterPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at mention.
        /// </summary>
        internal static string cmdRunAtMentionDialog {
            get {
                return ResourceManager.GetString("cmdRunAtMentionDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quiz.
        /// </summary>
        internal static string cmdRunQuiz {
            get {
                return ResourceManager.GetString("cmdRunQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send message to 1:1.
        /// </summary>
        internal static string cmdSend1on1ConversationDialog {
            get {
                return ResourceManager.GetString("cmdSend1on1ConversationDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setup text message.
        /// </summary>
        internal static string cmdSetupMessage {
            get {
                return ResourceManager.GetString("cmdSetupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setup card message.
        /// </summary>
        internal static string cmdUpdateCard {
            get {
                return ResourceManager.GetString("cmdUpdateCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update text message.
        /// </summary>
        internal static string cmdUpdateMessage {
            get {
                return ResourceManager.GetString("cmdUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to msgback.
        /// </summary>
        internal static string cmdValueMessageBack {
            get {
                return ResourceManager.GetString("cmdValueMessageBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to composeExtensionCardType.
        /// </summary>
        internal static string ComposeExtensionCardTypeKeyword {
            get {
                return ResourceManager.GetString("ComposeExtensionCardTypeKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Compose Extension is used as Compose Extension Sample. To change your settings either enter the work &apos;settings&apos; or change your settings on the settings menu option.To reset your configuration, simply enter the word &apos;reset&apos;..
        /// </summary>
        internal static string ComposeExtensionInitialRunText {
            get {
                return ResourceManager.GetString("ComposeExtensionInitialRunText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: No user data.
        /// </summary>
        internal static string ComposeExtensionNoUserData {
            get {
                return ResourceManager.GetString("ComposeExtensionNoUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to composeextension/querysettingurl.
        /// </summary>
        internal static string ComposeExtensionQuerySettingUrl {
            get {
                return ResourceManager.GetString("ComposeExtensionQuerySettingUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset.
        /// </summary>
        internal static string ComposeExtensionResetKeyword {
            get {
                return ResourceManager.GetString("ComposeExtensionResetKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your compose extension state has been reset..
        /// </summary>
        internal static string ComposeExtensionResetText {
            get {
                return ResourceManager.GetString("ComposeExtensionResetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setting.
        /// </summary>
        internal static string ComposeExtensionSettingKeyword {
            get {
                return ResourceManager.GetString("ComposeExtensionSettingKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        internal static string ComposeExtensionSettingsKeyword {
            get {
                return ResourceManager.GetString("ComposeExtensionSettingsKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static Tab Deep Link.
        /// </summary>
        internal static string DeepLinkCard1To1ButtonCaption {
            get {
                return ResourceManager.GetString("DeepLinkCard1To1ButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click below to navigate static tab.
        /// </summary>
        internal static string DeepLinkCard1To1Title {
            get {
                return ResourceManager.GetString("DeepLinkCard1To1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Tab Deep Link.
        /// </summary>
        internal static string DeepLinkCardConfigButtonCaption {
            get {
                return ResourceManager.GetString("DeepLinkCardConfigButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click below to navigate config tab.
        /// </summary>
        internal static string DeepLinkCardConfigTitle {
            get {
                return ResourceManager.GetString("DeepLinkCardConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose options to play with Sample App..
        /// </summary>
        internal static string DefaultDialogTitleMsg {
            get {
                return ResourceManager.GetString("DefaultDialogTitleMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is step1 in Root Dialog.
        /// </summary>
        internal static string DialogFlowStep1 {
            get {
                return ResourceManager.GetString("DialogFlowStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is step2 in Root Dialog.
        /// </summary>
        internal static string DialogFlowStep2 {
            get {
                return ResourceManager.GetString("DialogFlowStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is step3 in Root Dialog After triggering the Hello Dialog.
        /// </summary>
        internal static string DialogFlowStep3 {
            get {
                return ResourceManager.GetString("DialogFlowStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adaptive Card.
        /// </summary>
        internal static string DisplayCardAdaptiveCard {
            get {
                return ResourceManager.GetString("DisplayCardAdaptiveCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed with message:.
        /// </summary>
        internal static string DisplayCardErrorMsg {
            get {
                return ResourceManager.GetString("DisplayCardErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hero Card.
        /// </summary>
        internal static string DisplayCardHeroCard {
            get {
                return ResourceManager.GetString("DisplayCardHeroCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select any card.
        /// </summary>
        internal static string DisplayCardMsgTitle {
            get {
                return ResourceManager.GetString("DisplayCardMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connector Card Actions 2.
        /// </summary>
        internal static string DisplayCardO365ConnectorActionableCard2 {
            get {
                return ResourceManager.GetString("DisplayCardO365ConnectorActionableCard2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connector Card Actions.
        /// </summary>
        internal static string DisplayCardO365ConnectorActionableCardDefault {
            get {
                return ResourceManager.GetString("DisplayCardO365ConnectorActionableCardDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connector Card 2.
        /// </summary>
        internal static string DisplayCardO365ConnectorCard2 {
            get {
                return ResourceManager.GetString("DisplayCardO365ConnectorCard2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connector Card 3.
        /// </summary>
        internal static string DisplayCardO365ConnectorCard3 {
            get {
                return ResourceManager.GetString("DisplayCardO365ConnectorCard3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connector Card.
        /// </summary>
        internal static string DisplayCardO365ConnectorCardDefault {
            get {
                return ResourceManager.GetString("DisplayCardO365ConnectorCardDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What card you would like to test?.
        /// </summary>
        internal static string DisplayCardPromptText {
            get {
                return ResourceManager.GetString("DisplayCardPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to test another card?.
        /// </summary>
        internal static string DisplayCardsPromptChoiceTitle {
            get {
                return ResourceManager.GetString("DisplayCardsPromptChoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hope you liked the Cards!!.
        /// </summary>
        internal static string DisplayCardsThanksMsg {
            get {
                return ResourceManager.GetString("DisplayCardsThanksMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail Card.
        /// </summary>
        internal static string DisplayCardThumbnailCard {
            get {
                return ResourceManager.GetString("DisplayCardThumbnailCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for using Sample App.
        /// </summary>
        internal static string EndDialogTitleMsg {
            get {
                return ResourceManager.GetString("EndDialogTitleMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please setup card message using &quot;setup text message&quot; command before updating card..
        /// </summary>
        internal static string ErrorTextMessageUpdate {
            get {
                return ResourceManager.GetString("ErrorTextMessageUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating card message: .
        /// </summary>
        internal static string ErrorUpdatingCard {
            get {
                return ResourceManager.GetString("ErrorUpdatingCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Auth.
        /// </summary>
        internal static string FBAuthCardCaption {
            get {
                return ResourceManager.GetString("FBAuthCardCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fblogin.
        /// </summary>
        internal static string FBAuthCardValue {
            get {
                return ResourceManager.GetString("FBAuthCardValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to deserialize the Facebook response..
        /// </summary>
        internal static string FBAuthDeserializeError {
            get {
                return ResourceManager.GetString("FBAuthDeserializeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to User Profile.
        /// </summary>
        internal static string FBCardButtonCaption {
            get {
                return ResourceManager.GetString("FBCardButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To logged out from Facebook, use command &apos;fblogout&apos;.
        /// </summary>
        internal static string FBLginSuccessPromptLogoutInfo {
            get {
                return ResourceManager.GetString("FBLginSuccessPromptLogoutInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to Facebook!.
        /// </summary>
        internal static string FBLoginCardButtonCaption {
            get {
                return ResourceManager.GetString("FBLoginCardButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to authorize me.
        /// </summary>
        internal static string FBLoginCardPrompt {
            get {
                return ResourceManager.GetString("FBLoginCardPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already logged in, Enjoy your login session!!.
        /// </summary>
        internal static string FBLoginSessionExistsPrompt {
            get {
                return ResourceManager.GetString("FBLoginSessionExistsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are logged in as:.
        /// </summary>
        internal static string FBLoginSuccessPrompt {
            get {
                return ResourceManager.GetString("FBLoginSuccessPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login in using this card.
        /// </summary>
        internal static string FBLoginTitle {
            get {
                return ResourceManager.GetString("FBLoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To logged out from Facebook, use command &apos;fblogout&apos;.
        /// </summary>
        internal static string FBLogoutPrompt {
            get {
                return ResourceManager.GetString("FBLogoutPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To login again, use command &apos;fblogin&apos;!.
        /// </summary>
        internal static string FBSuccessfulLogoutLoginPrompt {
            get {
                return ResourceManager.GetString("FBSuccessfulLogoutLoginPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are logged out from Facebook acount!.
        /// </summary>
        internal static string FBSuccessfulLogoutPrompt {
            get {
                return ResourceManager.GetString("FBSuccessfulLogoutPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is Hello Dialog.
        /// </summary>
        internal static string HelloDialogMsg {
            get {
                return ResourceManager.GetString("HelloDialogMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At Mention.
        /// </summary>
        internal static string HelpCaptionAtMention {
            get {
                return ResourceManager.GetString("HelpCaptionAtMention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auth Sample.
        /// </summary>
        internal static string HelpCaptionAuthSample {
            get {
                return ResourceManager.GetString("HelpCaptionAuthSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Example.
        /// </summary>
        internal static string HelpCaptionDeepLink {
            get {
                return ResourceManager.GetString("HelpCaptionDeepLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog Flow.
        /// </summary>
        internal static string HelpCaptionDialogFlow {
            get {
                return ResourceManager.GetString("HelpCaptionDialogFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Cards.
        /// </summary>
        internal static string HelpCaptionDisplayCards {
            get {
                return ResourceManager.GetString("HelpCaptionDisplayCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch Last Dialog.
        /// </summary>
        internal static string HelpCaptionFetchLastDialog {
            get {
                return ResourceManager.GetString("HelpCaptionFetchLastDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch Members.
        /// </summary>
        internal static string HelpCaptionFetchRoster {
            get {
                return ResourceManager.GetString("HelpCaptionFetchRoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello Dialog.
        /// </summary>
        internal static string HelpCaptionHelloDialog {
            get {
                return ResourceManager.GetString("HelpCaptionHelloDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Back.
        /// </summary>
        internal static string HelpCaptionMessageBack {
            get {
                return ResourceManager.GetString("HelpCaptionMessageBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin Multi Dailog 1.
        /// </summary>
        internal static string HelpCaptionMultiDialog1 {
            get {
                return ResourceManager.GetString("HelpCaptionMultiDialog1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin Multi Dialog 2.
        /// </summary>
        internal static string HelpCaptionMultiDialog2 {
            get {
                return ResourceManager.GetString("HelpCaptionMultiDialog2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Game.
        /// </summary>
        internal static string HelpCaptionPlayGame {
            get {
                return ResourceManager.GetString("HelpCaptionPlayGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popup Sign-In.
        /// </summary>
        internal static string HelpCaptionPopUpSignIn {
            get {
                return ResourceManager.GetString("HelpCaptionPopUpSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch Roster Payload.
        /// </summary>
        internal static string HelpCaptionRosterPayload {
            get {
                return ResourceManager.GetString("HelpCaptionRosterPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RunQuiz.
        /// </summary>
        internal static string HelpCaptionRunQuiz {
            get {
                return ResourceManager.GetString("HelpCaptionRunQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send 1:1 Message.
        /// </summary>
        internal static string HelpCaptionSend1on1Conversation {
            get {
                return ResourceManager.GetString("HelpCaptionSend1on1Conversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Message.
        /// </summary>
        internal static string HelpCaptionSetupMessage {
            get {
                return ResourceManager.GetString("HelpCaptionSetupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Info.
        /// </summary>
        internal static string HelpCaptionTeamInfo {
            get {
                return ResourceManager.GetString("HelpCaptionTeamInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Card.
        /// </summary>
        internal static string HelpCaptionUpdateCard {
            get {
                return ResourceManager.GetString("HelpCaptionUpdateCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Message.
        /// </summary>
        internal static string HelpCaptionUpdateMessage {
            get {
                return ResourceManager.GetString("HelpCaptionUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Time.
        /// </summary>
        internal static string HelpLocalTimeZone {
            get {
                return ResourceManager.GetString("HelpLocalTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Options.
        /// </summary>
        internal static string HelpTitle {
            get {
                return ResourceManager.GetString("HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        internal static string HeroCardButtonCaption {
            get {
                return ResourceManager.GetString("HeroCardButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://sec.ch9.ms/ch9/7ff5/e07cfef0-aa3b-40bb-9baa-7c9ef8ff7ff5/buildreactionbotframework_960.jpg.
        /// </summary>
        internal static string HeroCardImageUrl {
            get {
                return ResourceManager.GetString("HeroCardImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bots — wherever your users are talking.
        /// </summary>
        internal static string HeroCardSubTitle {
            get {
                return ResourceManager.GetString("HeroCardSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build and connect intelligent bots to interact with your users naturally wherever they are, from text/sms to Skype, Slack, Office 365 mail and other popular services..
        /// </summary>
        internal static string HeroCardTextMsg {
            get {
                return ResourceManager.GetString("HeroCardTextMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BotFramework Hero Card.
        /// </summary>
        internal static string HeroCardTitle {
            get {
                return ResourceManager.GetString("HeroCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invokeKey.
        /// </summary>
        internal static string InvokeRequestJsonKey {
            get {
                return ResourceManager.GetString("InvokeRequestJsonKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionableMessageCardDialog.
        /// </summary>
        internal static string LastDialogActionableMessageDialog {
            get {
                return ResourceManager.GetString("LastDialogActionableMessageDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdaptiveCardDialog.
        /// </summary>
        internal static string LastDialogAdaptiveCard {
            get {
                return ResourceManager.GetString("LastDialogAdaptiveCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AtMentionDialog.
        /// </summary>
        internal static string LastDialogAtMentionDialog {
            get {
                return ResourceManager.GetString("LastDialogAtMentionDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeginDialog.
        /// </summary>
        internal static string LastDialogBeginDialog {
            get {
                return ResourceManager.GetString("LastDialogBeginDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O365ConnectorCardDailog.
        /// </summary>
        internal static string LastDialogConnectorCard {
            get {
                return ResourceManager.GetString("LastDialogConnectorCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectorCardDialog.
        /// </summary>
        internal static string LastDialogConnectorCardDialog {
            get {
                return ResourceManager.GetString("LastDialogConnectorCardDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeepLinkStaticTabDialog.
        /// </summary>
        internal static string LastDialogDeepLinkStaticTabDialog {
            get {
                return ResourceManager.GetString("LastDialogDeepLinkStaticTabDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayCardsDialog.
        /// </summary>
        internal static string LastDialogDisplayCardsDialog {
            get {
                return ResourceManager.GetString("LastDialogDisplayCardsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error finding last executed dialog.
        /// </summary>
        internal static string LastDialogErrorMsg {
            get {
                return ResourceManager.GetString("LastDialogErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimpleFacebookAuthDialog.
        /// </summary>
        internal static string LastDialogFacebookDialog {
            get {
                return ResourceManager.GetString("LastDialogFacebookDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FetchLastDialogName.
        /// </summary>
        internal static string LastDialogFetchDiaog {
            get {
                return ResourceManager.GetString("LastDialogFetchDiaog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FetchPayloadRosterDialog.
        /// </summary>
        internal static string LastDialogFetchPayloadRosterDialog {
            get {
                return ResourceManager.GetString("LastDialogFetchPayloadRosterDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FetchRosterDialog.
        /// </summary>
        internal static string LastDialogFetchRosterDialog {
            get {
                return ResourceManager.GetString("LastDialogFetchRosterDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FetchTeamInfoDialog.
        /// </summary>
        internal static string LastDialogFetchTeamInfoDialog {
            get {
                return ResourceManager.GetString("LastDialogFetchTeamInfoDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GameDialog.
        /// </summary>
        internal static string LastDialogGameDialog {
            get {
                return ResourceManager.GetString("LastDialogGameDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HelloDialog.
        /// </summary>
        internal static string LastDialogHelloDialog {
            get {
                return ResourceManager.GetString("LastDialogHelloDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HelpDialog.
        /// </summary>
        internal static string LastDialogHelpDialog {
            get {
                return ResourceManager.GetString("LastDialogHelpDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HeroCardDialog.
        /// </summary>
        internal static string LastDialogHeroCard {
            get {
                return ResourceManager.GetString("LastDialogHeroCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogId.
        /// </summary>
        internal static string LastDialogKey {
            get {
                return ResourceManager.GetString("LastDialogKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Back Dailog.
        /// </summary>
        internal static string LastDialogMessageBackDialog {
            get {
                return ResourceManager.GetString("LastDialogMessageBackDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiDialog1.
        /// </summary>
        internal static string LastDialogMultiDialog1 {
            get {
                return ResourceManager.GetString("LastDialogMultiDialog1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiDialog2.
        /// </summary>
        internal static string LastDialogMultiDialog2 {
            get {
                return ResourceManager.GetString("LastDialogMultiDialog2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PopUpSignInDialog.
        /// </summary>
        internal static string LastDialogPopUpSignIn {
            get {
                return ResourceManager.GetString("LastDialogPopUpSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last response was from dialog: .
        /// </summary>
        internal static string LastDialogPromptMsg {
            get {
                return ResourceManager.GetString("LastDialogPromptMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz1 Dialog.
        /// </summary>
        internal static string LastDialogQuiz1Dialog {
            get {
                return ResourceManager.GetString("LastDialogQuiz1Dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz2 Dialog.
        /// </summary>
        internal static string LastDialogQuiz2Dialog {
            get {
                return ResourceManager.GetString("LastDialogQuiz2Dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz Dialog.
        /// </summary>
        internal static string LastDialogQuizDialog {
            get {
                return ResourceManager.GetString("LastDialogQuizDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send 1:1 Dialog.
        /// </summary>
        internal static string LastDialogSend1on1Dialog {
            get {
                return ResourceManager.GetString("LastDialogSend1on1Dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetupTextMessageDialog.
        /// </summary>
        internal static string LastDialogSetupMessasge {
            get {
                return ResourceManager.GetString("LastDialogSetupMessasge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetupUpdateCardMsgDialog.
        /// </summary>
        internal static string LastDialogSetupUpdateCard {
            get {
                return ResourceManager.GetString("LastDialogSetupUpdateCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThumbnailcardDailog.
        /// </summary>
        internal static string LastDialogThumbnailCard {
            get {
                return ResourceManager.GetString("LastDialogThumbnailCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateLastTextMessageDialog.
        /// </summary>
        internal static string LastDialogUpdateMessasge {
            get {
                return ResourceManager.GetString("LastDialogUpdateMessasge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VSTSAuthDialog.
        /// </summary>
        internal static string LastDialogVSTSDialog {
            get {
                return ResourceManager.GetString("LastDialogVSTSDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Liked!!.
        /// </summary>
        internal static string LikeMessage {
            get {
                return ResourceManager.GetString("LikeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is Local Time - .
        /// </summary>
        internal static string LocalTimeZonePrompt {
            get {
                return ResourceManager.GetString("LocalTimeZonePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to initialRun.
        /// </summary>
        internal static string manifestInitialRun {
            get {
                return ResourceManager.GetString("manifestInitialRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to query.
        /// </summary>
        internal static string manifestParameterName {
            get {
                return ResourceManager.GetString("manifestParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message.
        /// </summary>
        internal static string MessageActivity {
            get {
                return ResourceManager.GetString("MessageActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Back.
        /// </summary>
        internal static string MessageBackCardButtonCaption {
            get {
                return ResourceManager.GetString("MessageBackCardButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is Displayed Text for Message Back.
        /// </summary>
        internal static string MessageBackDisplayedText {
            get {
                return ResourceManager.GetString("MessageBackDisplayedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is Message Back PayLoad Text..
        /// </summary>
        internal static string MessageBackPayloadText {
            get {
                return ResourceManager.GetString("MessageBackPayloadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is Message Back example.
        /// </summary>
        internal static string MessageBackTitleMsg {
            get {
                return ResourceManager.GetString("MessageBackTitleMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi Dialog Card Sub Title..
        /// </summary>
        internal static string MultiDialogCardSubTitle {
            get {
                return ResourceManager.GetString("MultiDialogCardSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi Dialog Card Text.
        /// </summary>
        internal static string MultiDialogCardText {
            get {
                return ResourceManager.GetString("MultiDialogCardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi Dialog Card Title..
        /// </summary>
        internal static string MultiDialogCardTitle {
            get {
                return ResourceManager.GetString("MultiDialogCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No message to update..
        /// </summary>
        internal static string NoMsgToUpdate {
            get {
                return ResourceManager.GetString("NoMsgToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is Null.
        /// </summary>
        internal static string NullException {
            get {
                return ResourceManager.GetString("NullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the text1.
        /// </summary>
        internal static string O365V1Section1 {
            get {
                return ResourceManager.GetString("O365V1Section1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the text2.
        /// </summary>
        internal static string O365V1Section2 {
            get {
                return ResourceManager.GetString("O365V1Section2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string O365V1Title {
            get {
                return ResourceManager.GetString("O365V1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch upload for TAX data on db-srv-hr1 aborted due to timeout. (ref324).
        /// </summary>
        internal static string O365V2ActivityTitle {
            get {
                return ResourceManager.GetString("O365V2ActivityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Time.
        /// </summary>
        internal static string O365V2Fact1Key {
            get {
                return ResourceManager.GetString("O365V2Fact1Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2016-05-30T16:50:02.503Z.
        /// </summary>
        internal static string O365V2Fact1Value {
            get {
                return ResourceManager.GetString("O365V2Fact1Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.
        /// </summary>
        internal static string O365V2Fact2Key {
            get {
                return ResourceManager.GetString("O365V2Fact2Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to omi10svr.
        /// </summary>
        internal static string O365V2Fact2Value {
            get {
                return ResourceManager.GetString("O365V2Fact2Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string O365V2Fact3Key {
            get {
                return ResourceManager.GetString("O365V2Fact3Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to job.
        /// </summary>
        internal static string O365V2Fact3Value {
            get {
                return ResourceManager.GetString("O365V2Fact3Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string O365V2Fact4Key {
            get {
                return ResourceManager.GetString("O365V2Fact4Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to medium.
        /// </summary>
        internal static string O365V2Fact4Value {
            get {
                return ResourceManager.GetString("O365V2Fact4Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fe9a13.
        /// </summary>
        internal static string O365V2themecolor {
            get {
                return ResourceManager.GetString("O365V2themecolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **New major event on omi10svr**.
        /// </summary>
        internal static string O365V2Title {
            get {
                return ResourceManager.GetString("O365V2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9/13/2016, 11:46am.
        /// </summary>
        internal static string O365V3ActivitySubtitle {
            get {
                return ResourceManager.GetString("O365V3ActivitySubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miguel Garcia.
        /// </summary>
        internal static string O365V3ActivityTitle {
            get {
                return ResourceManager.GetString("O365V3ActivityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository.
        /// </summary>
        internal static string O365V3Fact1Key {
            get {
                return ResourceManager.GetString("O365V3Fact1Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mgarcia\\test.
        /// </summary>
        internal static string O365V3Fact1Value {
            get {
                return ResourceManager.GetString("O365V3Fact1Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue #:.
        /// </summary>
        internal static string O365V3Fact2Key {
            get {
                return ResourceManager.GetString("O365V3Fact2Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 176715375.
        /// </summary>
        internal static string O365V3Fact2Value {
            get {
                return ResourceManager.GetString("O365V3Fact2Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://connectorsdemo.azurewebsites.net/images/MSC12_Oscar_002.jpg.
        /// </summary>
        internal static string O365V3ImageUrl {
            get {
                return ResourceManager.GetString("O365V3ImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue 176715375.
        /// </summary>
        internal static string O365V3Summary {
            get {
                return ResourceManager.GetString("O365V3Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem with Push notifications, they don&apos;t seem to be picked up by the connector..
        /// </summary>
        internal static string O365V3Text {
            get {
                return ResourceManager.GetString("O365V3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0078D7.
        /// </summary>
        internal static string O365V3ThemeColor {
            get {
                return ResourceManager.GetString("O365V3ThemeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue opened: Push notifications not working.
        /// </summary>
        internal static string O365V3Title {
            get {
                return ResourceManager.GetString("O365V3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please paste 12345 magic number in Bot to validate.
        /// </summary>
        internal static string OAuthCallbackMessage {
            get {
                return ResourceManager.GetString("OAuthCallbackMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please copy and paste the number returned after logging in..
        /// </summary>
        internal static string OAuthCallbackUserPrompt {
            get {
                return ResourceManager.GetString("OAuthCallbackUserPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        internal static string OptionNo {
            get {
                return ResourceManager.GetString("OptionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        internal static string OptionYes {
            get {
                return ResourceManager.GetString("OptionYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to payload roster.
        /// </summary>
        internal static string payloadrosterOptionValue {
            get {
                return ResourceManager.GetString("payloadrosterOptionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi! Nice to meet you .
        /// </summary>
        internal static string PlayGameAnswerForName {
            get {
                return ResourceManager.GetString("PlayGameAnswerForName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choice1.
        /// </summary>
        internal static string PlayGameChoice1 {
            get {
                return ResourceManager.GetString("PlayGameChoice1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choice2.
        /// </summary>
        internal static string PlayGameChoice2 {
            get {
                return ResourceManager.GetString("PlayGameChoice2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awwww man! I&apos;m still in the prototype phase..
        /// </summary>
        internal static string PlayGameFailMsg {
            get {
                return ResourceManager.GetString("PlayGameFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi!  I&apos;m a bot.  What is your name?.
        /// </summary>
        internal static string PlayGamePromptForName {
            get {
                return ResourceManager.GetString("PlayGamePromptForName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you pick,.
        /// </summary>
        internal static string PlayGameReplyMsg {
            get {
                return ResourceManager.GetString("PlayGameReplyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s play a game! You pick a button, and I will repeat it..
        /// </summary>
        internal static string PlayGameStartMsg {
            get {
                return ResourceManager.GetString("PlayGameStartMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yay!!!! What a fun game!.
        /// </summary>
        internal static string PlayGameThanksMsg {
            get {
                return ResourceManager.GetString("PlayGameThanksMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Choice.
        /// </summary>
        internal static string PlayGameWrongChoice {
            get {
                return ResourceManager.GetString("PlayGameWrongChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string PopUpSignInCardButtonTitle {
            get {
                return ResourceManager.GetString("PopUpSignInCardButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click below for Popup Sign-In experience.
        /// </summary>
        internal static string PopUpSignInCardTitle {
            get {
                return ResourceManager.GetString("PopUpSignInCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooops, what you choose is not a valid option, please try again!!.
        /// </summary>
        internal static string PromptInvalidMsg {
            get {
                return ResourceManager.GetString("PromptInvalidMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question 1.
        /// </summary>
        internal static string Quiz1Question {
            get {
                return ResourceManager.GetString("Quiz1Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for Completing Quiz 1.
        /// </summary>
        internal static string Quiz1ThanksTitleMsg {
            get {
                return ResourceManager.GetString("Quiz1ThanksTitleMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question 2.
        /// </summary>
        internal static string Quiz2Question {
            get {
                return ResourceManager.GetString("Quiz2Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Choice.
        /// </summary>
        internal static string QuizAnswerNo {
            get {
                return ResourceManager.GetString("QuizAnswerNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are Right.
        /// </summary>
        internal static string QuizAnswerYes {
            get {
                return ResourceManager.GetString("QuizAnswerYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin quiz dialog.
        /// </summary>
        internal static string QuizDialogBeginTitle {
            get {
                return ResourceManager.GetString("QuizDialogBeginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for playing fun quiz!!.
        /// </summary>
        internal static string QuizThanksTitleMsg {
            get {
                return ResourceManager.GetString("QuizThanksTitleMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi, Welcome to the fun quiz. Let&apos;s get started...
        /// </summary>
        internal static string QuizTitleWelcomeMsg {
            get {
                return ResourceManager.GetString("QuizTitleWelcomeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like Removed!!.
        /// </summary>
        internal static string RemoveLike {
            get {
                return ResourceManager.GetString("RemoveLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are the user information.
        /// </summary>
        internal static string RosterTitle {
            get {
                return ResourceManager.GetString("RosterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing the request for roster api user information!!.
        /// </summary>
        internal static string RosterWelcomeMsgTitle {
            get {
                return ResourceManager.GetString("RosterWelcomeMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1:1 Message sent.
        /// </summary>
        internal static string Send1on1ConfirmMsg {
            get {
                return ResourceManager.GetString("Send1on1ConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey! I am Bot, How&apos;s going!!.
        /// </summary>
        internal static string Send1on1Prompt {
            get {
                return ResourceManager.GetString("Send1on1Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle.
        /// </summary>
        internal static string SetupCardSubTitle {
            get {
                return ResourceManager.GetString("SetupCardSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string SetUpCardTitle {
            get {
                return ResourceManager.GetString("SetUpCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message set to be updated.
        /// </summary>
        internal static string SetupMessagePrompt {
            get {
                return ResourceManager.GetString("SetupMessagePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetUpMsgKey.
        /// </summary>
        internal static string SetUpMsgKey {
            get {
                return ResourceManager.GetString("SetUpMsgKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command only works in channels.
        /// </summary>
        internal static string TeamInfo1To1ConversationError {
            get {
                return ResourceManager.GetString("TeamInfo1To1ConversationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #PleaseSetTenantInformation.
        /// </summary>
        internal static string TenantConfigStaticValue {
            get {
                return ResourceManager.GetString("TenantConfigStaticValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS Teams: Attempted access from a different Office 365 tenant: message rejected.
        /// </summary>
        internal static string TenantLevelDeniedAccess {
            get {
                return ResourceManager.GetString("TenantLevelDeniedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for searching the Roster Api..
        /// </summary>
        internal static string ThanksRosterTitleMsg {
            get {
                return ResourceManager.GetString("ThanksRosterTitleMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        internal static string ThumbnailCardButtonCaption {
            get {
                return ResourceManager.GetString("ThumbnailCardButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://sec.ch9.ms/ch9/7ff5/e07cfef0-aa3b-40bb-9baa-7c9ef8ff7ff5/buildreactionbotframework_960.jpg.
        /// </summary>
        internal static string ThumbnailCardImageUrl {
            get {
                return ResourceManager.GetString("ThumbnailCardImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bots — wherever your users are talking.
        /// </summary>
        internal static string ThumbnailCardSubTitle {
            get {
                return ResourceManager.GetString("ThumbnailCardSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build and connect intelligent bots to interact with your users naturally wherever they are, from text/sms to Skype, Slack, Office 365 mail and other popular services..
        /// </summary>
        internal static string ThumbnailCardTextMsg {
            get {
                return ResourceManager.GetString("ThumbnailCardTextMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BotFramework Thumbnail Card.
        /// </summary>
        internal static string ThumbnailCardTitle {
            get {
                return ResourceManager.GetString("ThumbnailCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Card.
        /// </summary>
        internal static string UpdateCardButtonCaption {
            get {
                return ResourceManager.GetString("UpdateCardButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card updated - see above.
        /// </summary>
        internal static string UpdateCardMessageConfirmation {
            get {
                return ResourceManager.GetString("UpdateCardMessageConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSDN.
        /// </summary>
        internal static string UpdatedCardButtonCaption {
            get {
                return ResourceManager.GetString("UpdatedCardButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This card is updated now.
        /// </summary>
        internal static string UpdatedCardSubTitle {
            get {
                return ResourceManager.GetString("UpdatedCardSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated card .
        /// </summary>
        internal static string UpdatedCardTitle {
            get {
                return ResourceManager.GetString("UpdatedCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message updated - see above.
        /// </summary>
        internal static string UpdateMessageConfirmation {
            get {
                return ResourceManager.GetString("UpdateMessageConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message has been updated.
        /// </summary>
        internal static string UpdateMessagePrompt {
            get {
                return ResourceManager.GetString("UpdateMessagePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is UTC time -.
        /// </summary>
        internal static string UTCTimeZonePrompt {
            get {
                return ResourceManager.GetString("UTCTimeZonePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue:.
        /// </summary>
        internal static string VSTSApiIssue {
            get {
                return ResourceManager.GetString("VSTSApiIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Issue:.
        /// </summary>
        internal static string VSTSApiRequestError {
            get {
                return ResourceManager.GetString("VSTSApiRequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VSTS Auth.
        /// </summary>
        internal static string VSTSAuthCardCaption {
            get {
                return ResourceManager.GetString("VSTSAuthCardCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vstslogin.
        /// </summary>
        internal static string VSTSAuthCardValue {
            get {
                return ResourceManager.GetString("VSTSAuthCardValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VSTSAuthToken.
        /// </summary>
        internal static string VSTSAuthTokenKey {
            get {
                return ResourceManager.GetString("VSTSAuthTokenKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is some internal error!!.
        /// </summary>
        internal static string VSTSCallbackAuthError {
            get {
                return ResourceManager.GetString("VSTSCallbackAuthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Work Item.
        /// </summary>
        internal static string VSTSGetWorkItemCardButtonCaption {
            get {
                return ResourceManager.GetString("VSTSGetWorkItemCardButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry. In order to use this functionality you must log in..
        /// </summary>
        internal static string VSTSGetWorkItemLoginPrompt {
            get {
                return ResourceManager.GetString("VSTSGetWorkItemLoginPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the id of the work item you are looking for?.
        /// </summary>
        internal static string VSTSGetWorkItemPrompt {
            get {
                return ResourceManager.GetString("VSTSGetWorkItemPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to VSTS!.
        /// </summary>
        internal static string VSTSLoginCardButtonCaption {
            get {
                return ResourceManager.GetString("VSTSLoginCardButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to authorize me.
        /// </summary>
        internal static string VSTSLoginCardTitle {
            get {
                return ResourceManager.GetString("VSTSLoginCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already logged in VSTS, Enjoy your login session!!.
        /// </summary>
        internal static string VSTSLoginSessionExistsPrompt {
            get {
                return ResourceManager.GetString("VSTSLoginSessionExistsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are successfully logged-in!!.
        /// </summary>
        internal static string VSTSLoginSuccessPrompt {
            get {
                return ResourceManager.GetString("VSTSLoginSuccessPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login in using this card.
        /// </summary>
        internal static string VSTSLoginTitle {
            get {
                return ResourceManager.GetString("VSTSLoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To logged out from VSTS, use command &apos;vstslogout&apos;.
        /// </summary>
        internal static string VSTSlogoutPrompt {
            get {
                return ResourceManager.GetString("VSTSlogoutPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To login again, use command &apos;vstslogin&apos;!.
        /// </summary>
        internal static string VSTSSuccessfulLogoutLoginPrompt {
            get {
                return ResourceManager.GetString("VSTSSuccessfulLogoutLoginPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are logged out from VSTS acount!.
        /// </summary>
        internal static string VSTSSuccessfulLogoutPrompt {
            get {
                return ResourceManager.GetString("VSTSSuccessfulLogoutPrompt", resourceCulture);
            }
        }
    }
}
