version: '3'
services:
  Python:
    image: mcr.microsoft.com/devcontainers/python:1-3.8-bookworm
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: sleep infinity
    links:
      - nodejs
    # ...

  nodejs:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bookworm
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: sleep infinity
    links:
      - csharp
    # ...

  csharp:
    image: mcr.microsoft.com/devcontainers/dotnet:0-6.0
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: sleep infinity
    # ...