// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System.Text.RegularExpressions;
using Microsoft.Teams.Apps;
using Microsoft.Teams.Apps.Activities;
using Microsoft.Teams.Apps.Activities.Invokes;
using Microsoft.Teams.Api;
using Microsoft.Teams.Api.Cards;
using Microsoft.Teams.Cards;
using Microsoft.Teams.Plugins.AspNetCore.Extensions;
using MsgExt = Microsoft.Teams.Api.MessageExtensions;
using Newtonsoft.Json.Linq;
using AdaptiveCard = Microsoft.Teams.Cards.AdaptiveCard;

var builder = WebApplication.CreateBuilder(args);

builder.AddTeams();

var app = builder.Build();

var teams = app.UseTeams();

teams.OnQuery(async (ctx) =>
{
    var commandId = ctx.Activity.Value.CommandId;
    var parameters = ctx.Activity.Value.Parameters;
    var query = parameters?.FirstOrDefault()?.Value?.ToString() ?? "";

    Console.WriteLine($"Query: command={commandId}, query={query}");

    var attachments = new List<MsgExt.Attachment>();

    // Route to appropriate search
    if (commandId == "wikipediaSearch")
    {
        var results = await SearchWikipedia(query);
        attachments = results.Select(r =>
        {
            var title = r["title"]?.ToString() ?? "No Title";
            var snippet = Regex.Replace(r["snippet"]?.ToString() ?? "", "<[^>]+>", "");
            return CreateAttachment(CreateWikipediaCard(r), title, snippet);
        }).ToList();
    }

    if (attachments.Count == 0)
    {
        return new MsgExt.Response
        {
            ComposeExtension = new MsgExt.Result
            {
                Type = MsgExt.ResultType.Message,
                Text = $"No results found for '{query}'"
            }
        };
    }

    return new MsgExt.Response
    {
        ComposeExtension = new MsgExt.Result
        {
            Type = MsgExt.ResultType.Result,
            AttachmentLayout = Attachment.Layout.List,
            Attachments = attachments
        }
    };
});

teams.OnQueryLink((ctx) =>
{
    return Task.FromResult(CardResultResponse(CreateLinkPreviewCard(ctx.Activity.Value?.Url ?? "")));
});

teams.OnMessage(async (ctx) =>
{
    var text = (ctx.Activity.Text ?? "").ToLowerInvariant();

    if (text.Contains("help"))
    {
        await ctx.Send(
            "Hi! I'm the Search Messaging Extension Bot!\n\n" +
            "Use me in the compose area to search for Wikipedia articles\n");
    }
    else
    {
        await ctx.Send($"You said: {ctx.Activity.Text}\n\nType 'help' to learn more.");
    }
});

app.Run();


static AdaptiveCard CreateWikipediaCard(JToken result)
{
    var title = result["title"]?.ToString() ?? "No Title";
    var snippet = Regex.Replace(result["snippet"]?.ToString() ?? "", "<[^>]+>", "");

    return new AdaptiveCard()
    {
        Version = Microsoft.Teams.Cards.Version.Version1_4,
        Body = [
            new TextBlock(title) { Weight = TextWeight.Bolder, Size = TextSize.Large },
            new TextBlock(snippet) { Wrap = true, IsSubtle = true }
        ],
        Actions = [
            new OpenUrlAction($"https://en.wikipedia.org/wiki/{title.Replace(' ', '_')}") { Title = "Read on Wikipedia" }
        ]
    };
}

static AdaptiveCard CreateLinkPreviewCard(string url)
{
    return new AdaptiveCard()
    {
        Version = Microsoft.Teams.Cards.Version.Version1_4,
        Body = [
            new TextBlock("Link Preview") { Weight = TextWeight.Bolder, Size = TextSize.Medium },
            new TextBlock($"URL: {url}") { IsSubtle = true, Wrap = true },
            new TextBlock("This is a preview of the linked content generated by the message extension.") { Wrap = true, Size = TextSize.Small }
        ]
    };
}

static async Task<List<JToken>> SearchWikipedia(string query)
{
    if (string.IsNullOrWhiteSpace(query))
        return new List<JToken>();

    try
    {
        using var httpClient = new HttpClient();
        httpClient.DefaultRequestHeaders.UserAgent.ParseAdd("BotMessageExtensions/1.0 (Teams Bot; +https://example.com)");

        var parameters = new Dictionary<string, string>
        {
            ["action"] = "query",
            ["format"] = "json",
            ["list"] = "search",
            ["srsearch"] = query,
            ["utf8"] = "1",
            ["srlimit"] = "8"
        };

        var queryString = string.Join("&", parameters.Select(p => $"{p.Key}={Uri.EscapeDataString(p.Value)}"));
        var url = $"https://en.wikipedia.org/w/api.php?{queryString}";

        var response = await httpClient.GetStringAsync(url);
        var json = JObject.Parse(response);
        var searchResults = json["query"]?["search"] as JArray;

        return searchResults?.ToList() ?? new List<JToken>();
    }
    catch (Exception ex)
    {
        Console.WriteLine($"Wikipedia search error: {ex.Message}");
        return new List<JToken>();
    }
}

static MsgExt.Attachment CreateAttachment(AdaptiveCard card, string title, string text)
{
    return new MsgExt.Attachment(ContentType.AdaptiveCard)
    {
        Content = card,
        Preview = new Attachment(new ThumbnailCard
        {
            Title = title,
            Text = text
        })
    };
}

static MsgExt.Response CardResultResponse(AdaptiveCard card)
{
    return new MsgExt.Response
    {
        ComposeExtension = new MsgExt.Result
        {
            Type = MsgExt.ResultType.Result,
            AttachmentLayout = Attachment.Layout.List,
            Attachments = new List<MsgExt.Attachment>
            {
                new MsgExt.Attachment(ContentType.AdaptiveCard) { Content = card }
            }
        }
    };
}
