// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System.Text.Json;
using System.Text.RegularExpressions;
using Microsoft.Teams.Apps;
using Microsoft.Teams.Apps.MessageExtensions;
using Microsoft.Teams.Apps.Schema;
using Microsoft.Teams.Cards;
using Newtonsoft.Json.Linq;

var builder = WebApplication.CreateSlimBuilder(args);

builder.Services.AddTeamsBotApplication();

var app = builder.Build();

var teams = app.UseTeamsBotApplication();

teams.OnQuery(async (context, cancellationToken) =>
{
    MessageExtensionQuery? messageExtensionQuery = context.Activity.Value;
    var commandId = messageExtensionQuery?.CommandId;
    var parameters = messageExtensionQuery?.Parameters;
    var query = parameters?.FirstOrDefault()?.Value?.ToString() ?? "";

    Console.WriteLine($"Query: command={commandId}, query={query}");

    var attachments = new List<TeamsAttachment>();

    // Route to appropriate search
    if (commandId == "wikipediaSearch")
    {
        var results = await SearchWikipedia(query);
        attachments = results.Select(r =>
        {
            var title = r["title"]?.ToString() ?? "No Title";
            var snippet = Regex.Replace(r["snippet"]?.ToString() ?? "", "<[^>]+>", "");
            return CreateSearchResultAttachment(title, snippet);
        }).ToList();
    }

    if (attachments.Count == 0)
    {
        return MessageExtensionResponse.CreateBuilder()
            .WithType(MessageExtensionResponseTypes.Message)
            .WithText($"No results found for '{query}'")
            .Build();
    }

    return MessageExtensionResponse.CreateBuilder()
        .WithType(MessageExtensionResponseTypes.Result)
        .WithAttachmentLayout(TeamsAttachmentLayouts.List)
        .WithAttachments([.. attachments])
        .Build();
});

teams.OnQueryLink((context, cancellationToken) =>
{
    var url = context.Activity.Value?.Url?.ToString() ?? "";
    return Task.FromResult(CardResultResponse(CreateLinkPreviewCard(url)));
});

teams.OnMessage(async (context, cancellationToken) =>
{
    var text = (context.Activity.Text ?? "").ToLowerInvariant();

    if (text.Contains("help"))
    {
        await context.SendAsync(
            "Hi! I'm the Search Messaging Extension Bot!\n\n" +
            "Use me in the compose area to search for Wikipedia articles\n",
            cancellationToken);
    }
    else
    {
        await context.SendAsync(
            $"You said: {context.Activity.Text}\n\nType 'help' to learn more.",
            cancellationToken);
    }
});

app.Run();

static AdaptiveCard CreateLinkPreviewCard(string url)
{
    return new AdaptiveCard()
    {
        Version = Microsoft.Teams.Cards.Version.Version1_4,
        Body = [
            new TextBlock("Link Preview") { Weight = TextWeight.Bolder, Size = TextSize.Medium },
            new TextBlock($"URL: {url}") { IsSubtle = true, Wrap = true },
            new TextBlock("This is a preview of the linked content generated by the message extension.") { Wrap = true, Size = TextSize.Small }
        ]
    };
}

static async Task<List<JToken>> SearchWikipedia(string query)
{
    if (string.IsNullOrWhiteSpace(query))
        return new List<JToken>();

    try
    {
        using var httpClient = new HttpClient();
        httpClient.DefaultRequestHeaders.UserAgent.ParseAdd("BotMessageExtensions/1.0 (Teams Bot; +https://example.com)");

        var parameters = new Dictionary<string, string>
        {
            ["action"] = "query",
            ["format"] = "json",
            ["list"] = "search",
            ["srsearch"] = query,
            ["utf8"] = "1",
            ["srlimit"] = "8"
        };

        var queryString = string.Join("&", parameters.Select(p => $"{p.Key}={Uri.EscapeDataString(p.Value)}"));
        var url = $"https://en.wikipedia.org/w/api.php?{queryString}";

        var response = await httpClient.GetStringAsync(url);
        var json = JObject.Parse(response);
        var searchResults = json["query"]?["search"] as JArray;

        return searchResults?.ToList() ?? new List<JToken>();
    }
    catch (Exception ex)
    {
        Console.WriteLine($"Wikipedia search error: {ex.Message}");
        return new List<JToken>();
    }
}

static TeamsAttachment CreateSearchResultAttachment(string title, string text)
{
    return TeamsAttachment.CreateBuilder()
        .WithContent(new { title, text })
        .WithContentType(AttachmentContentTypes.ThumbnailCard)
        .Build();
}

static InvokeResponse<MessageExtensionResponse> CardResultResponse(AdaptiveCard card)
{
    var attachment = TeamsAttachment.CreateBuilder()
        .WithAdaptiveCard(JsonSerializer.SerializeToElement(card))
        .Build();

    return MessageExtensionResponse.CreateBuilder()
        .WithType(MessageExtensionResponseTypes.Result)
        .WithAttachmentLayout(TeamsAttachmentLayouts.List)
        .WithAttachments(attachment)
        .Build();
}
