// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import {
  cardAttachment,
  ThumbnailCard,
  MessagingExtensionAttachment,
  MessagingExtensionResponse,
} from '@microsoft/teams.api'
import { App } from '@microsoft/teams.apps'
import {
  AdaptiveCard,
  TextBlock,
  OpenUrlAction,
  ActionSet,
} from '@microsoft/teams.cards'
import axios from 'axios'

const app = new App()

app.on('message.ext.query', async ({ activity }) => {
  const commandId = activity.value?.commandId
  const params = activity.value?.parameters || []
  const query = params[0]?.value || ''
  console.log(`Query: command=${commandId}, query=${query}`)
  let attachments: MessagingExtensionAttachment[] = []

  if (commandId === 'wikipediaSearch') {
    const results = await searchWikipedia(query)
    attachments = results.map((r: any) =>
      createAttachment(
        createWikipediaCard(r),
        r.title,
        (r.snippet || '').replace(/<[^>]+>/g, '')
      )
    )
  }

  if (!attachments.length) {
    return {
      composeExtension: {
        type: 'message',
        text: `No results found for '${query}'`,
      },
    }
  }

  return {
    composeExtension: {
      type: 'result',
      attachmentLayout: 'list',
      attachments,
    },
  }
})

app.on('message.ext.query-link', async ({ activity }) => {
  return _cardResultResponse(createLinkPreviewCard(activity.value?.url || ''))
})

app.on('message', async ({ send, activity }) => {
  const text = (activity.text || '').toLowerCase()

  if (text.includes('help')) {
    await send(
      "Hi! I'm the Search Messaging Extension Bot!\n\n" +
        'Use me in the compose area to search for Wikipedia articles\n'
    )
  } else {
    await send(`You said: ${activity.text}\n\nType 'help' to learn more.`)
  }
})

function createWikipediaCard(result: Record<string, any>): AdaptiveCard {
  const title = result.title || 'No Title'
  const snippet = (result.snippet || '').replace(/<[^>]+>/g, '')
  const titleBlock = new TextBlock(title, { weight: 'Bolder', size: 'Large' })
  const snippetBlock = new TextBlock(snippet, { wrap: true, isSubtle: true })

  return new AdaptiveCard(
    titleBlock,
    snippetBlock,
    new ActionSet(
      new OpenUrlAction(`https://en.wikipedia.org/wiki/${title.replace(/ /g, '_')}`, { title: 'Read on Wikipedia' })
    )
  )
}

function createLinkPreviewCard(url: string): AdaptiveCard {
  const headerBlock = new TextBlock('Link Preview', { weight: 'Bolder', size: 'Medium' })
  const urlBlock = new TextBlock(`URL: ${url}`, { isSubtle: true, wrap: true })
  const descBlock = new TextBlock(
    'This is a preview of the linked content generated by the message extension.',
    { wrap: true, size: 'Small' }
  )

  return new AdaptiveCard(headerBlock, urlBlock, descBlock)
}

async function searchWikipedia(query: string): Promise<any[]> {
  if (!query) {
    return []
  }
  try {
    const params = new URLSearchParams({
      action: 'query',
      format: 'json',
      list: 'search',
      srsearch: query,
      utf8: '1',
      srlimit: '8',
    })
    const url = `https://en.wikipedia.org/w/api.php?${params.toString()}`
    const response = await axios.get(url, {
      headers: {
        'User-Agent': 'BotMessageExtensions/1.0 (Teams Bot; +https://example.com)',
      },
      timeout: 10000,
    })
    return response.data?.query?.search || []
  } catch (error) {
    console.error('Wikipedia search error:', error)
  }
  return []
}

function createAttachment(
  card: AdaptiveCard,
  title: string,
  text: string
): MessagingExtensionAttachment {
  const attachment = cardAttachment('adaptive', card)
  const preview = cardAttachment('thumbnail', { title, text } as ThumbnailCard)
  return {
    contentType: attachment.contentType,
    content: attachment.content,
    preview,
  }
}

function _cardResultResponse(card: AdaptiveCard): MessagingExtensionResponse {
  const attachment = cardAttachment('adaptive', card)
  return {
    composeExtension: {
      type: 'result',
      attachmentLayout: 'list',
      attachments: [
        {
          contentType: attachment.contentType,
          content: attachment.content,
        },
      ],
    },
  }
}

app.start().catch(console.error)
