// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import { CitationAppearance, MessageActivity, SensitiveUsageEntity } from "@microsoft/teams.api";
import { AdaptiveCard, TextBlock } from "@microsoft/teams.cards";
import { App } from "@microsoft/teams.apps";

const app = new App();

app.on("message.submit.feedback", async (context) => {
  try {
    const activity = context.activity;
    const reaction = activity.value?.actionValue?.reaction || "No reaction";
    const rawFeedback = activity.value?.actionValue?.feedback;
    const feedback = rawFeedback
      ? JSON.parse(rawFeedback).feedbackText || "No feedback was provided."
      : "No feedback was provided.";

    await context.send(`Provided reaction: ${reaction}<br> Feedback: ${feedback}`);
  } catch (err) {
    console.log(`Error in invoke activity: ${err}`);
  }
});

app.message(/label/i, async ({ send }) => {
  await send(new MessageActivity("Hi, this message is generated by AI").addAiGenerated());
});

app.message(/sensitivity/i, async ({ send }) => {
  const entity: SensitiveUsageEntity = {
    type: "https://schema.org/Message",
    "@type": "Message",
    "@context": "https://schema.org",
    "@id": "",
    usageInfo: {
      type: "https://schema.org/Message",
      "@type": "CreativeWork",
      description: "Please be mindful of sharing outside of your team",
      name: "Confidential \\ Contoso FTE",
    }
  };
  await send({
    type: 'message',
    text: "This is an example of a sensitivity label that help users identify the confidentiality of a message",
    entities: [entity]
  });
});

app.message(/feedback/i, async ({ send }) => {
  await send(new MessageActivity("This is an example of a feedback button - this helps to provide feedback for a message").addFeedback());
});

app.message(/citation/i, async ({ send }) => {
  const card = new AdaptiveCard(new TextBlock("Adaptive Card text"))
    .withOptions({ version: "1.6" });
  const appearance: CitationAppearance = {
    name: "AI messages bot",
    url: "https://example.com/claim-1",
    abstract: "Excerpt description",
    text: JSON.stringify(card),
    keywords: ["keyword 1", "keyword 2", "keyword 3"],
    icon: "Microsoft Word",
  };
  await send(
    new MessageActivity("Hey I'm a friendly AI bot. This message is generated through AI [1]")
      .addCitation(1, appearance)
  );
});

app.on("message", async ({ send }) => {
  await send("Welcome to the AI bot! Try sending messages with keywords like 'label', 'sensitivity', 'feedback', or 'citation' to see different AI features.");
});

app.start().catch(console.error);
