# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

import asyncio
import re
from typing import List, Dict, Any
from urllib.parse import urlencode
import httpx
from dotenv import load_dotenv
from microsoft_teams.api import (
    MessageActivity,
    MessageActivityInput,
    MessageExtensionQueryInvokeActivity,
    MessageExtensionQueryLinkInvokeActivity,
    card_attachment,
    AdaptiveCardAttachment,
    ThumbnailCard,
    ThumbnailCardAttachment,
    AttachmentLayout,
    MessagingExtensionAttachment,
    MessagingExtensionInvokeResponse,
    MessagingExtensionResult,
    MessagingExtensionResultType,
)
from microsoft_teams.apps import ActivityContext, App
from microsoft_teams.cards import (
    AdaptiveCard,
    TextBlock,
    OpenUrlAction,
)

load_dotenv()
app = App()

@app.on_message_ext_query
async def handle_query(ctx: ActivityContext[MessageExtensionQueryInvokeActivity]):
    command_id = ctx.activity.value.command_id
    params = ctx.activity.value.parameters or []
    query = params[0].value if params else ""
    
    print(f"Query: command={command_id}, query={query}")
    
    # Route to appropriate search
    if command_id == "wikipediaSearch":
        results = await search_wikipedia(query)
        attachments = [create_attachment(create_wikipedia_card(r), r['title'], re.sub(r'<[^>]+>', '', r.get('snippet', ''))) 
                      for r in results]
    
    if not attachments:
        return MessagingExtensionInvokeResponse(
        compose_extension=MessagingExtensionResult(
            type=MessagingExtensionResultType.MESSAGE,
            text=f"No results found for '{query}'"
        )
    )
    
    return MessagingExtensionInvokeResponse(
        compose_extension=MessagingExtensionResult(
            type=MessagingExtensionResultType.RESULT,
            attachment_layout=AttachmentLayout.LIST,
            attachments=attachments
        )
    )

@app.on_message_ext_query_link
async def handle_link(ctx: ActivityContext[MessageExtensionQueryLinkInvokeActivity]):
    return _card_result_response(create_link_preview_card(ctx.activity.value.url))


@app.on_message
async def handle_message(ctx: ActivityContext[MessageActivity]) -> None:
    text = (ctx.activity.text or "").lower()
    
    if "help" in text:
        await ctx.send(MessageActivityInput(
            text="Hi! I'm the Search Messaging Extension Bot!\n\n"
                 "Use me in the compose area to search for Wikipedia articles\n"
        ))
    else:
        await ctx.send(MessageActivityInput(text=f"You said: {ctx.activity.text}\n\nType 'help' to learn more."))

def create_wikipedia_card(result: Dict[str, Any]) -> AdaptiveCard:
    title = result.get('title', 'No Title')
    snippet = re.sub(r'<[^>]+>', '', result.get('snippet', ''))
    
    return AdaptiveCard(
        body=[
            TextBlock(text=title, weight="Bolder", size="Large"),
            TextBlock(text=snippet, wrap=True, is_subtle=True),
        ],
        actions=[
            OpenUrlAction(title="Read on Wikipedia", url=f"https://en.wikipedia.org/wiki/{title.replace(' ', '_')}")
        ]
    )

def create_link_preview_card(url: str) -> AdaptiveCard:
    return AdaptiveCard(
        body=[
            TextBlock(text="Link Preview", weight="Bolder", size="Medium"),
            TextBlock(text=f"URL: {url}", is_subtle=True, wrap=True),
            TextBlock(text="This is a preview of the linked content generated by the message extension.", 
                     wrap=True, size="Small")
        ]
    )

async def search_wikipedia(query: str) -> List[Dict[str, Any]]:
    if not query:
        return []
    try:
        params = {"action": "query", "format": "json", "list": "search", "srsearch": query, "utf8": 1, "srlimit": 8}
        url = f"https://en.wikipedia.org/w/api.php?{urlencode(params)}"
        async with httpx.AsyncClient(timeout=10) as client:
            resp = await client.get(url, headers={"User-Agent": "BotMessageExtensions/1.0 (Teams Bot; +https://example.com)"})
            resp.raise_for_status()
            return resp.json().get("query", {}).get("search", [])
    except Exception as e:
        print(f"Wikipedia search error: {e}")
    return []

def create_attachment(card: AdaptiveCard, title: str, text: str) -> MessagingExtensionAttachment:
    attachment = card_attachment(AdaptiveCardAttachment(content=card))
    preview = card_attachment(ThumbnailCardAttachment(content=ThumbnailCard(title=title, text=text, images=None)))
    return MessagingExtensionAttachment(
        content_type=attachment.content_type,
        content=attachment.content,
        preview=preview
    )

def _card_result_response(card: AdaptiveCard) -> MessagingExtensionInvokeResponse:
    attachment = card_attachment(AdaptiveCardAttachment(content=card))
    return MessagingExtensionInvokeResponse(
        compose_extension=MessagingExtensionResult(
            type=MessagingExtensionResultType.RESULT,
            attachment_layout=AttachmentLayout.LIST,
            attachments=[MessagingExtensionAttachment(content_type=attachment.content_type, content=attachment.content)]
        )
    )

if __name__ == "__main__":
    asyncio.run(app.start())
