// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license.

const crypto = require('crypto');
const http = require('http');

// Token generated by Teams
const sharedSecret = "<Security token generated by Microsoft Teams>"; // e.g. "+ZaRRMC8+mpnfGaGsBOmkIFt98bttL5YQRq3p2tXgcE="
const bufSecret = Buffer.from(sharedSecret, "base64");

const PORT = process.env.port || process.env.PORT || 3978;

http.createServer((request, response) => {
    let payload = '';

    request.on('data', (data) => {
        payload += data;
    });

    request.on('end', () => {
        try {
            const auth = request.headers['authorization'];
            const msgBuf = Buffer.from(payload, 'utf8');
            const msgHash = "HMAC " + crypto.createHmac('sha256', bufSecret).update(msgBuf).digest("base64");

            let responseMsg = '';

            if (msgHash === auth) {
                const receivedMsg = JSON.parse(payload);
                const receivedText = receivedMsg.text;

                switch (true) {
                    case receivedText.includes("adaptive-card"):
                        responseMsg = JSON.stringify({
                            type: "message",
                            attachments: [
                                {
                                    contentType: "application/vnd.microsoft.card.adaptive",
                                    content: {
                                        type: "AdaptiveCard",
                                        version: "1.5",
                                        body: [
                                            {
                                                type: "TextBlock",
                                                text: "Request sent by: " + receivedMsg.from.name
                                            },
                                            {
                                                type: "Image",
                                                url: "https://adaptivecards.io/content/cats/1.png"
                                            },
                                            {
                                                type: "TextBlock",
                                                text: "Sample image for Adaptive Card."
                                            }
                                        ]
                                    }
                                }
                            ]
                        });
                        break;

                    case receivedText.includes("hero-card"):
                        responseMsg = JSON.stringify({
                            type: "message",
                            attachments: [
                                {
                                    contentType: "application/vnd.microsoft.card.hero",
                                    content: {
                                        title: "Seattle Center Monorail",
                                        subtitle: "Seattle Center Monorail",
                                        text: "The Seattle Center Monorail is an elevated train line between Seattle Center (near the Space Needle) and downtown Seattle. It was built for the 1962 World's Fair. Its original two trains, completed in 1961, are still in service.",
                                        images: [
                                            {
                                                url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Seattle_monorail01_2008-02-25.jpg/1024px-Seattle_monorail01_2008-02-25.jpg"
                                            }
                                        ],
                                        buttons: [
                                            {
                                                type: "openUrl",
                                                title: "Official website",
                                                value: "https://www.seattlemonorail.com"
                                            },
                                            {
                                                type: "openUrl",
                                                title: "Wikipedia page",
                                                value: "https://en.wikipedia.org/wiki/Seattle_Center_Monorail"
                                            }
                                        ]
                                    }
                                }
                            ]
                        });
                        break;

                    case receivedText.includes("list-card"):
                        responseMsg = JSON.stringify({
                            type: "message",
                            attachments: [
                                {
                                    contentType: "application/vnd.microsoft.teams.card.list",
                                    content: {
                                        title: "Card title",
                                        items: [
                                            {
                                                type: "file",
                                                id: "https://contoso.sharepoint.com/teams/new/Shared%20Documents/Report.xlsx",
                                                title: "Report",
                                                subtitle: "teams > new > design",
                                                tap: {
                                                    type: "imBack",
                                                    value: "editOnline https://contoso.sharepoint.com/teams/new/Shared%20Documents/Report.xlsx"
                                                }
                                            },
                                            {
                                                type: "resultItem",
                                                icon: "https://cdn2.iconfinder.com/data/icons/social-icons-33/128/Trello-128.png",
                                                title: "Trello title",
                                                subtitle: "A Trello subtitle",
                                                tap: {
                                                    type: "openUrl",
                                                    value: "https://trello.com"
                                                }
                                            },
                                            {
                                                type: "section",
                                                title: "Manager"
                                            },
                                            {
                                                type: "person",
                                                id: "JohnDoe@contoso.com",
                                                title: "John Doe",
                                                subtitle: "Manager",
                                                tap: {
                                                    type: "imBack",
                                                    value: "whois JohnDoe@contoso.com"
                                                }
                                            }
                                        ],
                                        buttons: [
                                            {
                                                type: "imBack",
                                                title: "Select",
                                                value: "whois"
                                            }
                                        ]
                                    }
                                }
                            ]
                        });
                        break;

                    case receivedText.includes("o365-card"):
                        responseMsg = JSON.stringify({
                            type: "message",
                            attachments: [
                                {
                                    contentType: "application/vnd.microsoft.teams.card.o365connector",
                                    content: {
                                        "@type": "MessageCard",
                                        "@context": "http://schema.org/extensions",
                                        summary: "John Doe commented on Trello",
                                        title: "Project Tango",
                                        sections: [
                                            {
                                                activityTitle: "John Doe commented",
                                                activitySubtitle: "On Project Tango",
                                                activityText: "\"Here are the designs\"",
                                                activityImage: "https://adaptivecards.io/content/cats/1.png"
                                            },
                                            {
                                                title: "Details",
                                                facts: [
                                                    {
                                                        name: "Labels",
                                                        value: "Designs, redlines"
                                                    },
                                                    {
                                                        name: "Due date",
                                                        value: "Dec 7, 2016"
                                                    },
                                                    {
                                                        name: "Attachments",
                                                        value: "[final.jpg](https://adaptivecards.io/content/cats/1.png)"
                                                    }
                                                ]
                                            }
                                        ],
                                        potentialAction: [
                                            {
                                                "@context": "http://schema.org",
                                                "@type": "ViewAction",
                                                name: "View in Trello",
                                                target: [
                                                    "https://trello.com/c/1101/"
                                                ]
                                            }
                                        ]
                                    }
                                }
                            ]
                        });
                        break;

                    case receivedText.includes("thumbnail-card"):
                        responseMsg = JSON.stringify({
                            type: "message",
                            attachments: [
                                {
                                    contentType: "application/vnd.microsoft.card.thumbnail",
                                    content: {
                                        title: "Bender",
                                        subtitle: "tale of a robot who dared to love",
                                        text: "Bender Bending Rodríguez is a main character in the animated television series Futurama. He was created by series creators Matt Groening and David X. Cohen, and is voiced by John DiMaggio",
                                        images: [
                                            {
                                                url: "https://upload.wikimedia.org/wikipedia/en/a/a6/Bender_Rodriguez.png",
                                                alt: "Bender Rodríguez"
                                            }
                                        ],
                                        buttons: [
                                            {
                                                type: "imBack",
                                                title: "Thumbs Up",
                                                value: "I like it"
                                            },
                                            {
                                                type: "imBack",
                                                title: "Thumbs Down",
                                                value: "I don't like it"
                                            },
                                            {
                                                type: "openUrl",
                                                title: "I feel lucky",
                                                value: "https://www.bing.com/images/search?q=bender&qpvt=bender&FORM=IGRE"
                                            }
                                        ],
                                        tap: {
                                            type: "imBack",
                                            value: "Tapped it!"
                                        }
                                    }
                                }
                            ]
                        });
                        break;

                    default:
                        responseMsg = JSON.stringify({
                            type: "message",
                            text: `**You typed**: ${receivedMsg.text}\n**Commands supported**: adaptive-card, hero-card, list-card, o365-card, and thumbnail-card`
                        });
                        break;
                }
            } else {
                responseMsg = JSON.stringify({
                    type: "message",
                    text: "Error: message sender cannot be authenticated."
                });
            }

            response.writeHead(200, { 'Content-Type': 'application/json' });
            response.end(responseMsg);
        } catch (err) {
            response.writeHead(400);
            response.end(`Error: ${err}\n${err.stack}`);
        }
    });

}).listen(PORT, (error) => {
    if (error) {
        console.log(error);
        process.exit(1);
    } else {
        console.log(`Listening on port: ${PORT}`);
    }
});