//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.QBot.Infrastructure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Apps.QBot.Infrastructure.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answered by.
        /// </summary>
        public static string answeredBy {
            get {
                return ResourceManager.GetString("answeredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marked as answered by {0}..
        /// </summary>
        public static string answeredBySummary {
            get {
                return ResourceManager.GetString("answeredBySummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application commands are supported in Teams channel only..
        /// </summary>
        public static string commandContextNotSupportedErrorMessage {
            get {
                return ResourceManager.GetString("commandContextNotSupportedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string commandContextNotSupportedErrorTitle {
            get {
                return ResourceManager.GetString("commandContextNotSupportedErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application doesn&apos;t support this command..
        /// </summary>
        public static string commandNotSupportedErrorMessage {
            get {
                return ResourceManager.GetString("commandNotSupportedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command not supported.
        /// </summary>
        public static string commandNotSupportedErrorTitle {
            get {
                return ResourceManager.GetString("commandNotSupportedErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% confidence. Is this answer helpful?.
        /// </summary>
        public static string confidence {
            get {
                return ResourceManager.GetString("confidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please install QBot to this team to get started..
        /// </summary>
        public static string courseNotFoundErrorMessage {
            get {
                return ResourceManager.GetString("courseNotFoundErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course not found .
        /// </summary>
        public static string courseNotFoundErrorTitle {
            get {
                return ResourceManager.GetString("courseNotFoundErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/images/create-new-thread.gif.
        /// </summary>
        public static string createNewThreadGIFUrl {
            get {
                return ResourceManager.GetString("createNewThreadGIFUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application doesn&apos;t support answering questions in an existing message thread. Start a new conversation and tag the application when you post a new question..
        /// </summary>
        public static string createNewThreadMessage {
            get {
                return ResourceManager.GetString("createNewThreadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to select an answer. Question author and educators may select an answer..
        /// </summary>
        public static string forbiddenToSelectAnswerErrorMessage {
            get {
                return ResourceManager.GetString("forbiddenToSelectAnswerErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not authorized.
        /// </summary>
        public static string forbiddenToSelectAnswerErrorTitle {
            get {
                return ResourceManager.GetString("forbiddenToSelectAnswerErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string generalChannelName {
            get {
                return ResourceManager.GetString("generalChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to answer.
        /// </summary>
        public static string goToAnswerButtonTitle {
            get {
                return ResourceManager.GetString("goToAnswerButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helpful.
        /// </summary>
        public static string helpful {
            get {
                return ResourceManager.GetString("helpful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} marked this as helpful..
        /// </summary>
        public static string helpfulAcceptedBy {
            get {
                return ResourceManager.GetString("helpfulAcceptedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not helpful.
        /// </summary>
        public static string notHelpful {
            get {
                return ResourceManager.GetString("notHelpful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} marked this as not helpful..
        /// </summary>
        public static string nothelpfulAcceptedBy {
            get {
                return ResourceManager.GetString("nothelpfulAcceptedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question is marked as answered..
        /// </summary>
        public static string questionIsAnsweredMessage {
            get {
                return ResourceManager.GetString("questionIsAnsweredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question is marked as answered..
        /// </summary>
        public static string questionMarkedAsAnsweredErrorMessage {
            get {
                return ResourceManager.GetString("questionMarkedAsAnsweredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot post answer.
        /// </summary>
        public static string questionMarkedAsAnsweredErrorTitle {
            get {
                return ResourceManager.GetString("questionMarkedAsAnsweredErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question not found. Please make sure you tag the bot while posting a question..
        /// </summary>
        public static string questionNotFoundErrorMessage {
            get {
                return ResourceManager.GetString("questionNotFoundErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question not found.
        /// </summary>
        public static string questionNotFoundErrorTitle {
            get {
                return ResourceManager.GetString("questionNotFoundErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select answer.
        /// </summary>
        public static string selectAnswer {
            get {
                return ResourceManager.GetString("selectAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select answer.
        /// </summary>
        public static string selectAnswerDialogTitle {
            get {
                return ResourceManager.GetString("selectAnswerDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure knowledge base, tutorial groups and user roles.
        /// </summary>
        public static string setupCoursePreviewText {
            get {
                return ResourceManager.GetString("setupCoursePreviewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagging educator(s) to help - {0}.
        /// </summary>
        public static string tagEducators {
            get {
                return ResourceManager.GetString("tagEducators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again..
        /// </summary>
        public static string unknownErrorMessage {
            get {
                return ResourceManager.GetString("unknownErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string unknownErrorTitle {
            get {
                return ResourceManager.GetString("unknownErrorTitle", resourceCulture);
            }
        }
    }
}
