// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

using Microsoft.Teams.Api;
using Microsoft.Teams.Api.Activities;
using Microsoft.Teams.Api.Entities;
using Microsoft.Teams.Apps;
using Microsoft.Teams.Apps.Activities;
using Microsoft.Teams.Apps.Activities.Invokes;
using Microsoft.Teams.Plugins.AspNetCore.Extensions;
using System.Text.Json;

var builder = WebApplication.CreateBuilder(args);
builder.AddTeams();

var app = builder.Build();
var teams = app.UseTeams();

teams.OnMessage(async context =>
{
    var text = context.Activity.Text?.Trim().ToLower() ?? "";

    if (text.Contains("label"))
        await SendAILabel(context);
    else if (text.Contains("feedback"))
        await SendFeedbackButtons(context);
    else if (text.Contains("sensitivity"))
        await SendSensitivityLabel(context);
    else if (text.Contains("citation"))
        await SendCitations(context);
    else
        await SendWelcomeCard(context);
});

teams.OnFeedback(async context =>
{
    var reaction = "No reaction";
    var feedbackText = "No feedback was provided.";

    var actionValue = context.Activity.Value.ActionValue;
    if (actionValue != null)
    {
        var json = JsonSerializer.Serialize(actionValue);
        using var doc = JsonDocument.Parse(json);
        var root = doc.RootElement;

        if (root.TryGetProperty("reaction", out var reactionProp))
            reaction = reactionProp.GetString() ?? "No reaction";

        if (root.TryGetProperty("feedback", out var feedbackProp))
        {
            var feedbackJsonStr = feedbackProp.GetString();
            if (!string.IsNullOrEmpty(feedbackJsonStr))
            {
                using var feedbackDoc = JsonDocument.Parse(feedbackJsonStr);
                if (feedbackDoc.RootElement.TryGetProperty("feedbackText", out var ftProp))
                    feedbackText = ftProp.GetString() ?? "No feedback was provided.";
            }
        }
    }

    await context.Send($"Provided reaction: {reaction}<br> Feedback: {feedbackText}");
});

async Task SendAILabel(IContext<MessageActivity> context)
{
    await context.Send(new MessageActivity
    {
        Text = "Hi, this message is generated by AI"
    }.AddAIGenerated());
}

async Task SendFeedbackButtons(IContext<MessageActivity> context)
{
    await context.Send(new MessageActivity("This is an example of a feedback button - this helps to provide feedback for a message")
        .AddFeedback());
}

async Task SendSensitivityLabel(IContext<MessageActivity> context)
{
    var entity = new CitationEntity();
    entity.Properties["@id"] = "";
    entity.Properties["usageInfo"] = JsonSerializer.SerializeToNode(new SensitiveUsageEntity
    {
        Name = "Confidential \\ Contoso FTE",
        Description = "Please be mindful of sharing outside of your team"
    });

    await context.Send(new MessageActivity
    {
        Text = "This is an example of a sensitivity label that help users identify the confidentiality of a message",
        Entities = new List<IEntity> { entity }
    });
}

async Task SendCitations(IContext<MessageActivity> context)
{
    var message = new MessageActivity
    {
        Text = "Hey I'm a friendly AI bot. This message is generated through AI [1]"
    };

    message.AddCitation(1, new CitationAppearance
    {
        Name = "AI messages bot",
        Url = "https://example.com/claim-1",
        Abstract = "Excerpt description",
        Keywords = new List<string> { "keyword 1", "keyword 2", "keyword 3" },
        Icon = CitationIcon.MicrosoftWord
    });

    await context.Send(message);
}

async Task SendWelcomeCard(IContext<MessageActivity> context)
{
    await context.Send("Welcome to the AI bot! Try sending messages with keywords like 'label', 'sensitivity', 'feedback', or 'citation' to see different AI features.");
}

app.Run();