// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

using Microsoft.Teams.Apps;
using Microsoft.Teams.Apps.Schema;
using Microsoft.Teams.Apps.Schema.Entities;
using System.Text.Json;

var builder = WebApplication.CreateSlimBuilder(args);

builder.Services.AddTeamsBotApplication();

var app = builder.Build();

var teams = app.UseTeamsBotApplication();

teams.OnMessage(async (context, cancellationToken) =>
{
    string text = context.Activity.Text?.Trim().ToLowerInvariant() ?? "";

    if (text.Contains("label"))
        await SendAILabelAsync(context, cancellationToken);
    else if (text.Contains("feedback"))
        await SendFeedbackButtonsAsync(context, cancellationToken);
    else if (text.Contains("sensitivity"))
        await SendSensitivityLabelAsync(context, cancellationToken);
    else if (text.Contains("citation"))
        await SendCitationsAsync(context, cancellationToken);
    else
        await SendWelcomeCardAsync(context, cancellationToken);
});

teams.OnMessageSubmitFeedback(async (context, cancellationToken) =>
{
    MessageSubmitFeedbackValue? feedback = context.Activity.Value;

    string reaction = feedback?.Reaction ?? "No reaction";
    string feedbackText = "No feedback was provided.";

    // Teams sends the feedback form inputs as a JSON-encoded string.
    if (!string.IsNullOrEmpty(feedback?.Feedback))
    {
        try
        {
            using JsonDocument feedbackDoc = JsonDocument.Parse(feedback.Feedback);
            if (feedbackDoc.RootElement.TryGetProperty("feedbackText", out JsonElement feedbackTextProp))
                feedbackText = feedbackTextProp.GetString() ?? feedbackText;
        }
        catch (JsonException)
        {
            feedbackText = feedback.Feedback;
        }
    }

    await context.SendAsync($"Provided reaction: {reaction}<br> Feedback: {feedbackText}", cancellationToken);

    return InvokeResponse.Ok();
});

static async Task SendAILabelAsync(Context<MessageActivity> context, CancellationToken cancellationToken)
{
    await context.SendAsync(
        new MessageActivityInput()
            .WithText("Hi, this message is generated by AI")
            .AddAIGenerated(),
        cancellationToken);
}

static async Task SendFeedbackButtonsAsync(Context<MessageActivity> context, CancellationToken cancellationToken)
{
    await context.SendAsync(
        new MessageActivityInput()
            .WithText("This is an example of a feedback button - this helps to provide feedback for a message")
            .AddFeedback(),
        cancellationToken);
}

static async Task SendSensitivityLabelAsync(Context<MessageActivity> context, CancellationToken cancellationToken)
{
    await context.SendAsync(
        new MessageActivityInput()
            .WithText("This is an example of a sensitivity label that help users identify the confidentiality of a message")
            .AddSensitivityLabel("Confidential \\ Contoso FTE", "Please be mindful of sharing outside of your team"),
        cancellationToken);
}

static async Task SendCitationsAsync(Context<MessageActivity> context, CancellationToken cancellationToken)
{
    await context.SendAsync(
        new MessageActivityInput()
            .WithText("Hey I'm a friendly AI bot. This message is generated through AI [1]", TextFormats.Markdown)
            .AddCitation(1, new CitationAppearance
            {
                Name = "AI messages bot",
                Url = new Uri("https://example.com/claim-1"),
                Abstract = "Excerpt description",
                Keywords = ["keyword 1", "keyword 2", "keyword 3"],
                Icon = CitationIcons.MicrosoftWord
            }),
        cancellationToken);
}

static async Task SendWelcomeCardAsync(Context<MessageActivity> context, CancellationToken cancellationToken)
{
    await context.SendAsync(
        "Welcome to the AI bot! Try sending messages with keywords like 'label', 'sensitivity', 'feedback', or 'citation' to see different AI features.",
        cancellationToken);
}

app.Run();