# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build - All Samples
on:
  push:
    #Change the branch name to <<main>>
    #Change the path to the folder where your code resides. Any change here will start the activity. 
    branches:
      - main
    paths:
      - '**'
  workflow_dispatch:
env:
    CI: false
jobs:
  build-csharp-samples:
    runs-on: windows-latest
    #Add project path, name and project runtime version as below for any new additions
    strategy:
      matrix:
        include:
            - project_path: 'samples/TeamsSDK/bot-ai-messages/dotnet/bot-ai-messages/BotAiMessages.csproj'
              name: 'bot-ai-messages'
              version: '10.0.x'

            - project_path: 'samples/TeamsSDK/bot-attachments/dotnet/bot-attachments/BotAttachments.csproj'
              name: 'bot-attachments'
              version: '10.0.x'

            - project_path: 'samples/TeamsSDK/bot-auth-quickstart/dotnet/bot-auth-quickstart/BotAuthQuickstart/BotAuthQuickstart.csproj'
              name: 'bot-auth-quickstart'
              version: '10.0.x'

            - project_path: 'samples/TeamsSDK/bot-cards/dotnet/bot-cards/BotCards.csproj'
              name: 'bot-cards'
              version: '10.0.x'

            - project_path: 'samples/TeamsSDK/bot-meetings/dotnet/bot-meetings/BotMeetings.csproj'
              name: 'bot-meetings'
              version: '10.0.x'

            - project_path: 'samples/TeamsSDK/bot-message-extensions/dotnet/bot-message-extensions/BotMessageExtensions.csproj'
              name: 'bot-message-extensions'
              version: '10.0.x'

            - project_path: 'samples/TeamsSDK/bot-quickstart/dotnet/bot-quickstart/BotQuickstart.csproj'
              name: 'bot-quickstart'
              version: '10.0.x'

            - project_path: 'samples/TeamsSDK/bot-task-modules/dotnet/bot-task-modules/BotTaskModules.csproj'
              name: 'bot-task-modules'
              version: '10.0.x'
           
            - project_path: 'samples/TeamsJS/app-sso/csharp/App SSO Sample/App SSO Sample.csproj'
              name: 'app-sso'
              version: '6.0.x'

            - project_path: 'samples/TeamsJS/graph-activity-feed-broadcast/csharp/ActivityFeedBroadcast/ActivityFeedBroadcast.csproj'
              name: 'graph-activity-feed-broadcast'
              version: '6.0.x'

            - project_path: 'samples/TeamsJS/graph-app-installation-lifecycle/csharp/AppInstallation/AppInstallation.csproj'
              name: 'graph-app-installation-lifecycle'
              version: '6.0.x'

            - project_path: 'samples/TeamsJS/graph-rsc/csharp/RSCDemo/RSCDemo.csproj'
              name: 'graph-rsc'
              version: '6.0.x'

            - project_path: 'samples/TeamsJS/meeting-recruitment-app/csharp/MeetingApp/MeetingApp.csproj'
              name: 'meeting-recruitment-app'
              version: '6.0.x'

            - project_path: 'samples/TeamsJS/meetings-details-tab/csharp/DetailsTab/DetailsTab.csproj'
              name: 'meetings-details-tab'
              version: '6.0.x'

            - project_path: 'samples/TeamsJS/meetings-live-code-interview/csharp/MeetingLiveCoding/MeetingLiveCoding.csproj'
              name: 'meetings-live-code-interview'
              version: '6.0.x'

            - project_path: 'samples/TeamsJS/meetings-sidepanel/csharp/SidePanel/SidePanel.csproj'
              name: 'meetings-sidepanel'
              version: '6.0.x'

            - project_path: 'samples/TeamsJS/meetings-stage-view/csharp/AppInMeeting/AppInMeeting.csproj'
              name: 'meetings-stage-view'
              version: '6.0.x'

            - project_path: 'samples/TeamsJS/meetings-token-app/csharp/TokenApp.csproj'
              name: 'meetings-token-app'
              version: '6.0.x'

            - project_path: 'samples/TeamsJS/msgext-link-unfurling-meeting/csharp/Source/Microsoft.Teams.Samples.LinkUnfurling.Web./Microsoft.Teams.Samples.LinkUnfurling.Web.csproj'
              name: 'msgext-link-unfurling-meeting'
              version: '6.0.x'

            - project_path: 'samples/TeamsJS/msgext-link-unfurling-reddit/csharp/dotnet/RLU.csproj'
              name: 'msgext-link-unfurling-reddit'
              version: '6.0.x'

            - project_path: 'samples/TeamsJS/msgext-link-unfurling-reddit/csharp/dotnet_user_auth/RLU.csproj'
              name: 'msgext-link-unfurling-reddit'
              version: '6.0.x'

            - project_path: 'samples/TeamsJS/tab-app-navigation/csharp/Microsoft.Teams.Samples.TabAppNavigation.Web/Microsoft.Teams.Samples.TabAppNavigation.Web.csproj'
              name: 'tab-app-navigation'
              version: '6.0.x'

            - project_path: 'samples/TeamsJS/tab-external-auth/csharp/TabExternalAuth/TabExternalAuth.csproj'
              name: 'tab-external-auth'
              version: '6.0.x'

            - project_path: 'samples/TeamsJS/tab-product-inspection/csharp/ProductInspection/ProductInspection.csproj'
              name: 'tab-product-inspection'
              version: '6.0.x'

            - project_path: 'samples/TeamsJS/tab-request-approval/csharp/TabRequestApproval/TabRequestApproval.csproj'
              name: 'tab-request-approval'
              version: '6.0.x'

            - project_path: 'samples/TeamsJS/tab-channel-group-quickstart/csharp/Microsoft.Teams.Samples.TabChannelGroupQuickstart.Web/Microsoft.Teams.Samples.TabChannelGroupQuickstart.Web.csproj'
              name: 'tab-channel-group-quickstart'
              version: '6.0.x'

            - project_path: 'samples/TeamsJS/tab-graph-toolkit/csharp/TabGraphToolkit/TabGraphToolkit.csproj'
              name: 'tab-graph-toolkit'
              version: '6.0.x'

            - project_path: 'samples/TeamsJS/tab-people-picker/csharp/TabPeoplePicker/TabPeoplePicker.csproj'
              name: 'tab-people-picker'
              version: '6.0.x'

            - project_path: 'samples/TeamsJS/tab-personal-sso-quickstart/csharp_dotnetcore/PersonalTabSSO.csproj'
              name: 'tab-personal-sso-quickstart'
              version: '6.0.x'

            - project_path: 'samples/TeamsJS/tab-channel-group/mvc-csharp/ChannelGroupTabMVC.csproj'
              name: 'tab-channel-group'
              version: '6.0.x'

            - project_path: 'samples/TeamsJS/tab-channel-group/razor-csharp/channelGroupTab.csproj'
              name: 'tab-channel-group'
              version: '6.0.x'

            - project_path: 'samples/TeamsJS/tab-channel-group-sso-quickstart/csharp_dotnetcore/GroupTabSSO.csproj'
              name: 'tab-channel-group-sso-quickstart'
              version: '6.0.x'

            - project_path: 'samples/TeamsJS/graph-bulk-meetings/csharp/EventMeeting/EventMeeting.csproj'
              name: 'graph-bulk-meetings'
              version: '6.0.x' 

            - project_path: 'samples/TeamsJS/graph-change-notification-team-channel/csharp/ChangeNotification/ChangeNotification.csproj'
              name: 'graph-change-notification-team-channel'
              version: '6.0.x' 

            - project_path: 'samples/TeamsJS/graph-pinned-messages/csharp/GraphPinnedMessage/GraphPinnedMessage.csproj'
              name: 'graph-pinned-messages'
              version: '6.0.x'

            - project_path: 'samples/TeamsJS/graph-teams-tag/csharp/GraphTeamsTag/GraphTeamsTag.csproj'
              name: 'graph-teams-tag'
              version: '6.0.x'

            - project_path: 'samples/TeamsJS/incoming-webhook/csharp/IncomingWebhook/IncomingWebhook.csproj'
              name: 'incoming-webhook'
              version: '6.0.x'

            - project_path: 'samples/TeamsJS/meetings-context-app/csharp/MeetingContextApp/MeetingContextApp.csproj'
              name: 'meetings-context-app'
              version: '6.0.x'

            - project_path: 'samples/TeamsJS/meetings-share-to-stage-signing/csharp/Source/MeetingSigning.Domain.Tests/Microsoft.Teams.Samples.MeetingSigning.Domain.Tests.csproj'
              name: 'meetings-share-to-stage-signing'
              version: '6.0.x'

            - project_path: 'samples/TeamsJS/meetings-share-to-stage-signing/csharp/Source/MeetingSigning.Domain/Microsoft.Teams.Samples.MeetingSigning.Domain.csproj'
              name: 'meetings-share-to-stage-signing'
              version: '6.0.x'

            - project_path: 'samples/TeamsJS/meetings-share-to-stage-signing/csharp/Source/MeetingSigning.Infrastructure.Tests/Microsoft.Teams.Samples.MeetingSigning.Infrastructure.Tests.csproj'
              name: 'meetings-share-to-stage-signing'
              version: '6.0.x'
              
            - project_path: 'samples/TeamsJS/meetings-share-to-stage-signing/csharp/Source/MeetingSigning.Infrastructure/Microsoft.Teams.Samples.MeetingSigning.Infrastructure.csproj'
              name: 'meetings-share-to-stage-signing'
              version: '6.0.x'

            - project_path: 'samples/TeamsJS/meetings-share-to-stage-signing/csharp/Source/MeetingSigning.Web.Tests/Microsoft.Teams.Samples.MeetingSigning.Web.Tests.csproj'
              name: 'meetings-share-to-stage-signing'
              version: '6.0.x'

            - project_path: 'samples/TeamsJS/meetings-share-to-stage-signing/csharp/Source/MeetingSigning.Web/Microsoft.Teams.Samples.MeetingSigning.Web.csproj'
              name: 'meetings-share-to-stage-signing'
              version: '6.0.x'

            - project_path: 'samples/TeamsJS/msteams-application-resourcehub/Source/microsoft-teams-apps-selfhelp/Microsoft.Teams.Apps.Selfhelp.csproj'
              name: 'msteams-application-resourcehub'
              version: '6.0.x' 

            - project_path: 'samples/TeamsJS/msteams-application-qbot/Source/Microsoft.Teams.App.Domain/Microsoft.Teams.Apps.QBot.Domain.csproj'
              name: 'msteams-application-qbot'
              version: '2.0'

            - project_path: 'samples/TeamsJS/msteams-application-qbot/Source/Microsoft.Teams.Apps.QBot.Infrastructure/Microsoft.Teams.Apps.QBot.Infrastructure.csproj'
              name: 'msteams-application-qbot'
              version: '3.1'

            - project_path: 'samples/TeamsJS/msteams-application-qbot/Source/Microsoft.Teams.Apps.QBot.Web/Microsoft.Teams.Apps.QBot.Web.csproj'
              name: 'msteams-application-qbot'
              version: '3.1'    

            - project_path: 'samples/TeamsJS/graph-activity-feed/csharp/ActivityFeedNotification/TabActivityFeed.csproj'
              name: 'graph-activity-feed'
              version: '6.0.x' 


      fail-fast: false
    name: Build All "${{ matrix.name }}" csharp
    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "${{ matrix.version }}"
          include-prerelease: true

      - name: Build app
        run: dotnet build "${{ matrix.project_path }}" --configuration Release

  build-nodejs-samples:
    runs-on: windows-latest
    #Add project path, name and version as below for any new additions
    strategy:
      matrix:
        include:
            - project_path: 'samples/TeamsJS/app-sso/nodejs'
              name: 'app-sso'
              version: '18.x'

            - project_path: 'samples/TeamsJS/app-sso/nodejs/client'
              name: 'app-sso-client'
              version: '18.x'

            - project_path: 'samples/TeamsJS/app-task-module/nodejs'
              name: 'app-task-module'
              version: '14.x'

            - project_path: 'samples/TeamsJS/connector-github-notification/nodejs'
              name: 'connector-github-notification'
              version: '14.x'
            
            - project_path: 'samples/TeamsJS/graph-activity-feed-broadcast/nodejs'
              name: 'graph-activity-feed-broadcast'
              version: '14.x'

            - project_path: 'samples/TeamsJS/graph-activity-feed/nodejs'
              name: 'graph-activity-feed'
              version: '14.x'

            - project_path: 'samples/TeamsJS/graph-app-installation-lifecycle/nodejs'
              name: 'graph-app-installation-lifecycle'
              version: '14.x'

            - project_path: 'samples/TeamsJS/graph-rsc/nodejs'
              name: 'graph-rsc'
              version: '14.x'

            - project_path: 'samples/TeamsJS/meetings-sidepanel/nodejs'
              name: 'meetings-sidepanel'
              version: '18.x'

            - project_path: 'samples/TeamsJS/meetings-sidepanel/nodejs/ClientApp'
              name: 'meetings-sidepanel-clientapp'
              version: '18.x'

            - project_path: 'samples/TeamsJS/meetings-stage-view/nodejs'
              name: 'meetings-stage-view'
              version: '14.x'
            
            - project_path: 'samples/TeamsJS/meetings-stage-view/nodejs/ClientApp'
              name: 'meetings-stage-view-clientapp'
              version: '14.x'

            - project_path: 'samples/TeamsJS/meetings-token-app/nodejs'
              name: 'meetings-token-app'
              version: '16.18.0'

            - project_path: 'samples/TeamsJS/meeting-recruitment-app/nodejs/api'
              name: 'meeting-recruitment-app'
              version: '16.8.x'

            - project_path: 'samples/TeamsJS/meeting-recruitment-app/nodejs'
              name: 'meeting-recruitment-app-clientapp'
              version: '16.8.x'

            - project_path: 'samples/TeamsJS/tab-product-inspection/nodejs'
              name: 'tab-product-inspection'
              version: '14.x'

            - project_path: 'samples/TeamsJS/tab-request-approval/nodejs'
              name: 'tab-request-approval'
              version: '14.x'

            - project_path: 'samples/TeamsJS/tab-people-picker/nodejs'
              name: 'tab-people-picker'
              version: '14.x'

            - project_path: 'samples/TeamsJS/tab-channel-group/nodejs'
              name: 'tab-channel-group'
              version: '16.x'

            - project_path: 'samples/TeamsJS/tab-channel-group-quickstart/js'
              name: 'tab-channel-group-quickstart'
              version: '14.x'

            - project_path: 'samples/TeamsJS/tab-channel-group-quickstart/ts'
              name: 'tab-channel-group-quickstart'
              version: '14.x'

            - project_path: 'samples/TeamsJS/tab-channel-group-sso-quickstart/js'
              name: 'tab-channel-group-sso-quickstart'
              version: '14.x'

            - project_path: 'samples/TeamsJS/tab-channel-group-sso-quickstart/js/api-server'
              name: 'tab-channel-group-sso-quickstart-api-server'
              version: '14.x'

            - project_path: 'samples/TeamsJS/tab-channel-group-sso-quickstart/ts'
              name: 'tab-channel-group-sso-quickstart'
              version: '14.x'

            - project_path: 'samples/TeamsJS/tab-channel-group-sso-quickstart/ts/api-server'
              name: 'tab-channel-group-sso-quickstart'
              version: '14.x'

            - project_path: 'samples/TeamsJS/tab-personal-quickstart/js'
              name: 'tab-personal-quickstart'
              version: '14.x'

            - project_path: 'samples/TeamsJS/tab-personal-quickstart/ts'
              name: 'tab-personal-quickstart'
              version: '14.x'

            - project_path: 'samples/TeamsJS/tab-personal-sso-quickstart/js'
              name: 'tab-personal-sso-quickstart'
              version: '18.x'

            - project_path: 'samples/TeamsJS/tab-personal-sso-quickstart/js/api-server'
              name: 'tab-personal-sso-quickstart-api-server'
              version: '18.x'

            - project_path: 'samples/TeamsJS/tab-personal-sso-quickstart/ts'
              name: 'tab-personal-sso-quickstart'
              version: '18.x'

            - project_path: 'samples/TeamsJS/tab-personal-sso-quickstart/ts/api-server'
              name: 'tab-personal-sso-quickstart-api-server'
              version: '18.x'

            - project_path: 'samples/TeamsJS/tab-graph-toolkit/nodejs'
              name: 'tab-graph-toolkit'
              version: '16.x'
            
            - project_path: 'samples/TeamsJS/graph-bulk-meetings/nodejs'
              name: 'graph-bulk-meetings'
              version: '16.x' 

            - project_path: 'samples/TeamsJS/graph-bulk-meetings/nodejs/client'
              name: 'graph-bulk-meetings-client'
              version: '16.x' 

            - project_path: 'samples/TeamsJS/graph-change-notification-team-channel/nodejs'
              name: 'graph-change-notification-team-channel'
              version: '16.x' 

            - project_path: 'samples/TeamsJS/graph-change-notification-team-channel/nodejs/client'
              name: 'graph-change-notification-team-channel-client'
              version: '16.x' 

            - project_path: 'samples/TeamsJS/graph-pinned-messages/nodejs'
              name: 'graph-pinned-messages'
              version: '16.x'

            - project_path: 'samples/TeamsJS/graph-pinned-messages/nodejs/ClientApp'
              name: 'graph-pinned-messages-clientapp'
              version: '16.x'

            - project_path: 'samples/TeamsJS/graph-teams-tag/nodejs'
              name: 'graph-teams-tag'
              version: '16.x'

            - project_path: 'samples/TeamsJS/graph-teams-tag/nodejs/client'
              name: 'graph-teams-tag-client'
              version: '16.x'

            - project_path: 'samples/TeamsJS/incoming-webhook/nodejs/ClientApp'
              name: 'incoming-webhook-client-app'
              version: '16.x'

            - project_path: 'samples/TeamsJS/incoming-webhook/nodejs/api'
              name: 'incoming-webhook-server-apis'
              version: '16.x'

            - project_path: 'samples/TeamsJS/tab-app-monetization/nodejs'
              name: 'tab-app-monetization'
              version: '16.x'

            - project_path: 'samples/TeamsJS/tab-device-permissions/nodejs'
              name: 'tab-device-permissions'
              version: '16.x'
            
            - project_path: 'samples/TeamsJS/tab-channel-context/nodejs'
              name: 'tab-channel-context'  
              version: '16.x'
            
            - project_path: 'samples/TeamsJS/meetings-audio-state/nodejs'
              name: 'meetings-audio-state'
              version: '16.x'

            - project_path: 'samples/TeamsJS/tab-ui-templates/ts'
              name: 'tab-ui-templates'
              version: '18.x'

            - project_path: 'samples/TeamsJS/tab-navbar-menu/ts'
              name: 'tab-navbar-menu'
              version: '16.x'
            
            - project_path: 'samples/TeamsJS/app-cache-meetings/nodejs'
              name: 'app-cache-meetings'
              version: '18.x'

            - project_path: 'samples/TeamsJS/app-anonymous-users/nodejs/ClientApp'
              name: 'app-anonymous-users-clientapp'
              version: '18.x'

            - project_path: 'samples/TeamsJS/app-anonymous-users/nodejs'
              name: 'app-anonymous-users-api'
              version: '18.x'

            - project_path: 'samples/TeamsJS/tab-multi-hub/ts/api-server'
              name: 'tab-multi-hub-api-server'
              version: '18.x'

            - project_path: 'samples/TeamsJS/tab-multi-hub/ts'
              name: 'tab-multi-hub'
              version: '18.x'
            
            - project_path: 'samples/TeamsJS/graph-rsc-helper/nodejs'
              name: 'graph-rsc-helper'
              version: '18.x'

            - project_path: 'samples/TeamsJS/tab-nested-auth/nodejs'
              name: 'tab-nested-auth'
              version: '18.x'
            
            - project_path: 'samples/TeamsJS/tab-adhoccalls-transcript-recording/nodejs'
              name: 'tab-adhoccalls-transcript-recording'
              version: '18.x'

            - project_path: 'samples/TeamsJS/tab-adhoccalls-transcript-recording/nodejs/api-server'
              name: 'tab-adhoccalls-transcript-recording-api-server'
              version: '18.x'

            - project_path: 'samples/TeamsJS/tab-meeting-transcript-recording/nodejs/api-server'
              name: 'tab-meeting-transcript-recording-api-server'
              version: '18.x'
              
            - project_path: 'samples/TeamsSDK/bot-ai-messages/nodejs/bot-ai-messages'
              name: 'bot-ai-messages'
              version: '20.x'

            - project_path: 'samples/TeamsSDK/bot-attachments/nodejs/bot-attachments'
              name: 'bot-attachments'
              version: '20.x'

            - project_path: 'samples/TeamsSDK/bot-auth-quickstart/nodejs/bot-auth-quickstart'
              name: 'bot-auth-quickstart'
              version: '20.x'

            - project_path: 'samples/TeamsSDK/bot-cards/nodejs/bot-cards'
              name: 'bot-cards'
              version: '20.x'

            - project_path: 'samples/TeamsSDK/bot-meetings/nodejs/bot-meetings'
              name: 'bot-meetings'
              version: '20.x'

            - project_path: 'samples/TeamsSDK/bot-message-extensions/nodejs/bot-message-extensions'
              name: 'bot-message-extensions'
              version: '20.x'

            - project_path: 'samples/TeamsSDK/bot-quickstart/nodejs/bot-quickstart'
              name: 'bot-quickstart'
              version: '20.x'

            - project_path: 'samples/TeamsSDK/bot-task-modules/nodejs/bot-task-modules'
              name: 'bot-task-modules'
              version: '20.x'


      fail-fast: false
    name: Build all "${{ matrix.name }}" nodejs
    defaults:
      run:
        working-directory: "${{ matrix.project_path }}"
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "${{ matrix.version }}"

      - name: npm install, build, and test
        run: |
          npm install
          npm run build

  build-python-samples:
    runs-on: windows-latest
    #Add project path, name and version as below for any new additions
    strategy:
      matrix:
        include:
            - project_path: 'samples/TeamsJS/graph-pinned-messages/python'
              name: 'graph-pinned-messages'
              version: '3.10.x'

            - project_path: 'samples/TeamsJS/tab-app-navigation/python'
              name: 'tab-app-navigation'
              version: '3.10.x'

            - project_path: 'samples/TeamsJS/graph-membership-change-notification/python'
              name: 'graph-membership-change-notification'
              version: '3.10.x'

            - project_path: 'samples/TeamsJS/tab-request-approval/python'
              name: 'tab-request-approval'
              version: '3.10.x'

            - project_path: 'samples/TeamsSDK/bot-ai-messages/python/bot-ai-messages'
              name: 'bot-ai-messages'
              version: '3.12.x'

            - project_path: 'samples/TeamsSDK/bot-attachments/python/bot-attachments'
              name: 'bot-attachments'
              version: '3.12.x'

            - project_path: 'samples/TeamsSDK/bot-auth-quickstart/python/bot-auth-quickstart'
              name: 'bot-auth-quickstart'
              version: '3.12.x'

            - project_path: 'samples/TeamsSDK/bot-cards/python/bot-cards'
              name: 'bot-cards'
              version: '3.12.x'

            - project_path: 'samples/TeamsSDK/bot-meetings/python/bot-meetings'
              name: 'bot-meetings'
              version: '3.12.x'

            - project_path: 'samples/TeamsSDK/bot-message-extensions/python/bot-message-extensions'
              name: 'bot-message-extensions'
              version: '3.12.x'

            - project_path: 'samples/TeamsSDK/bot-quickstart/python/bot-quickstart'
              name: 'bot-quickstart'
              version: '3.12.x'

            - project_path: 'samples/TeamsSDK/bot-task-modules/python/bot-task-modules'
              name: 'bot-task-modules'
              version: '3.12.x'

      fail-fast: false
    name: Build all "${{ matrix.name }}" python
    defaults:
      run:
        working-directory: "${{ matrix.project_path }}"
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.version }}"
          cache: 'pip'
      - name: Install dependencies
        run: |
          if (Test-Path requirements.txt) { pip install -r requirements.txt } else { pip install -e . }
